### ISSUE TITLE
Tags field fails when using number-only tags

### ISSUE THREAD

**Issue by azharc** [getkirby-v2/panel#1005]
When using a number-only tag, all actions will fail because the number is not being type-cast as a string and .toLowerCase() is failing.

To fix this issue, tag strings must be type-cast. Adding a .toString() method within the function below from panel.js solved the issue. 

```javascript
    // get an element by tag
    this.get = function(tag) {
      return self.elements.filter(function(i, element) {
        return $(this).data('tag') == tag.toString().toLowerCase();
      });
    };
```

**Comment by hentrev** [comment]
Hi Azhar,

thanks for the fix. I had the same problem.

Why did you not make a pull request or mark it as a bug?

Best regards
Henrik
