### ISSUE TITLE
URLs with leading number can be created in the Panel

### ISSUE THREAD

**Issue by malvese** [getkirby-v2/panel#1008]
(is related to #326 but this issue is specifically for the Panel)

When we create a page, if the name starts with numbers, imho there are two issues with the current interface:

1. The preview of the page ID shows the number but it is actually ignored when the page is created, which I think is confusing.
![preview](https://cloud.githubusercontent.com/assets/193492/23062401/e513f100-f505-11e6-8ebb-e43043d856ff.gif)
2. If the URL-appendix is modified manually or if the "Create from title" button is used, the Panel will *not* ignore the leading numbers this time, and let users create an invalid URL that can cause issues later if/when the page visibility is changed.
![url](https://cloud.githubusercontent.com/assets/193492/23062540/7d4c58cc-f506-11e6-91fd-c1bf9a04f815.gif)

Possible solutions:
- remove leading numbers automatically in previews and file names, imho the Panel should never let us make mistakes
- if we want to let people do it anyway, display a warning
- use another separator for sorting prefixes, but this is a whole different discussion

**Comment by puckey** [comment]
+1.. I noticed this too late and now have hundreds of pages with incorrect slugs: https://forum.getkirby.com/t/wrong-slug-when-creating-page-in-panel/8493

**Comment by d23levin** [comment]
+1, i also ran into this problem.
