### ISSUE TITLE
Deleting File Does Not Update Fields Inside Structure Fields

### ISSUE THREAD

**Issue by luxlogica** [getkirby-v2/panel#1024]
You have a page with a required image field. 
You upload an image to that page. You then select that image in the image field. Save. No problem.
You then delete the image from inside the page - in the 'Files' section, use the dropdown menu next to the file name, and select 'delete'. 
Result: the Panel very cleverly also deletes the image entry from our image field - ie., it knows that the image is being used by the field, and if we delete the image, it empties the field.

Now, let's say that instead of having the image field right there on the page, we have a required image field inside a *structure* field - i.e., we're using this so the user selects images for a slideshow on the page. The image is *required* for each slide.

Now, let's also go through the same steps: 
- upload an image to the page
- select the image inside one of our list entries
- save the page - great, we can see the image listed there.
- now, in the 'Files' section of the page, delete the image.

Result: the Panel does **NOT** empty the entry in the image field inside our structure field -ie., it does not check whether fields inside structures are using it...

This can cause fatal crashes, if the missing image is being also run through the *thumbs()* function. The developers get caught unawares, because they trust that the Panel is cleverly emptying all fields that might be using the image, when it gets deleted. Therefore, most of us will just check whether the field is *empty*, and assume that if the field is not empty, then the value it contains can safely be assumed to be an available image...

It would be great if the Panel could also check **inside structure fields** when images and files are deleted - not just page fields.

**Comment by texnixe** [comment]
> This can cause fatal crashes, if the missing image is being also run through the thumbs() function. The developers get caught unawares, because they trust that the Panel is cleverly emptying all fields that might be using the image, when it gets deleted. Therefore, most of us will just check whether the field is empty, and assume that if the field is not empty, then the value it contains can safely be assumed to be an available image...

Even if the Panel empties the field, if you don't save the changes or if the image is deleted otherwise, it is always necessary to check if the image exists before calling any method or function on it. Never rely solely on the `isNotEmpty()` method.

**Comment by luxlogica** [comment]
@texnixe Indeed, you're totally right. Indeed, I've tried to use the normal `$file->exists()` method, but this also caused a crash. I was assuming that `$page->image()` returns a file object, and that I would be able then to chain it to check whether it exists, like this: `$page->image()->exists()`.

Here is the scenario:

- we have a structure field in our page called *'slides'*
- inside this structure field, each slide will have a *'slideImage'* required field

```
// iterating through the entries in our structure field:
foreach($page->slides()->toStructure() as $slide): 

// first, check whether we have an image, and that it exists...:
   if($slide->slideimage()->isNotEmpty() && $page->image($slide->slideimage())->exists()):
// ... then, use thumb() to generate image at the right size:
```

What happens here, is that `$page->image()` fails to generate an image, so it returns `null` - and we can't do `null->exists()`... ;-) 

We can certainly check with php's own `empty()` and `is_null()` functions, but the obvious drawback here is that we don't know whether the interface of the `$page->image()` function is going to change in a future version of Kirby or not - e.g., return an object that can be chained with `->exists()`. Then, our checks for `null` will all need to be updated.

**Comment by texnixe** [comment]
The better way to do that would be:

```
if($image = $page->image($slide->slideimage()):
 // then use thumb() to generate thumb
endif
```
With this code, no matter if the field is empty or the field is not empty, but the image does not exist, you are always on the safe side.
