### ISSUE TITLE
Windows: Keyboard shortcuts work with both Ctrl and Alt, Alt shouldn't work

### ISSUE THREAD

**Issue by mciszczon** [getkirby-v2/panel#1028]
Is there an option to change or disable default keyboard shortcuts in the panel? Some of theme interfere with key combinations for various letters, for example Polish `ś` letter: `alt + s`. The same shortcut saves edits and refreshes the page. Needless to say it makes it impossible to write content in the panel.

I tried to find the place where this shortcut is storaged but I couldn't find it.

**Comment by lukasbestle** [comment]
Which operating system and browser are you using?

I'm asking because this is a bug. On macOS, the shortcuts use the Cmd key (Cmd-S etc.). They should use the meta key (Windows key on Windows) on other operating systems.

**Comment by medienbaecker** [comment]
@lukasbestle On my Windows system it only works pressing the Ctrl key, not the Windows key.

**Comment by mciszczon** [comment]
@lukasbestle 

Yeah, the same for me. It saves with `Ctrl + S`, it saves with `Alt + S`.
I've tested it on Linux and there's no bug. So the problem is Windows. I'm using Win 10.

**Comment by lukasbestle** [comment]
Sorry, of course it should be Ctrl on Windows, Windows key does not make sense. :)

**Comment by mciszczon** [comment]
Yes, `Meta + S` opens the search bar. So it should be `Ctrl` and surely not `Alt`. Thanks for the fast reaction, looking forward for a fix!

**Comment by mciszczon** [comment]
Anyone up to anything? ;)

**Comment by heidiv** [comment]
Also interested in disabling kb shortcuts! They seem to be interfering with accessibility keyboard commands. I'm using a navigation menu that is kb controlled but esc, up/down arrows, etc. are not working and I think this could be why. Thanks!
