### ISSUE TITLE
Don't show structure type table label th when there are no labels

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#1030]
In my case below I don't need a label because I only use one subfield. Still, the th is used and in this case it's not needed. This accurs when using `style: table`.

![image](https://cloud.githubusercontent.com/assets/927011/24601118/f974339c-1857-11e7-8da6-b7a9605537c5.png)

**Comment by lukasbestle** [comment]
Makes sense, we could introduce a blueprint option for the structure field to hide the labels in the table view.

Meanwhile, you can hide the first row with CSS.

**Comment by jenstornell** [comment]
Blueprint option to hide the labels is an even better idea.

It's not as magic and it solves two problems at the same time. It hides empty labels (when we want) and it hides labels in general, when we want.
