### ISSUE TITLE
checkboxes - multiple values

### ISSUE THREAD

**Issue by jensfranke** [getkirby-v2/panel#1038]
Based on the documentation (https://getkirby.com/docs/cheatsheet/panel-fields/checkboxes) the following way should work to set multiple values as default: 
```
default:  
      - architecture  
      - web  
```

in version 2.4.1 the following way works for me:
```
default: architecture, web  
```

**Comment by texnixe** [comment]
What is the issue here? The documentation is correct? Even if the second version works as well?

**Comment by jensfranke** [comment]
this way don't work for me:

```
default:  
      - architecture  
      - web  
```

**Comment by texnixe** [comment]
I can't reproduce this. Did you test in a fresh Starterkit?

**Comment by jensfranke** [comment]
Yes, fresh Starterkit. YAML-File is also valid with `indent_style=space` and `indent_size=2`.

In the end it's fine for me too use this way:

`default: architecture, web`
