### ISSUE TITLE
Toggle field to "No" crashes the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#1043]
A new fresh installation of Kirby 2.4.1 throws an error when a toggle field is used. I first saved "Yes" and then tried to save "No". The panel crashed on "No".

>Missing argument 1 for KirbyPanelModelsPage::toggle(), called in C:xampphtdocskirby2.4.1.4panelappsrcpanelmodelspagechanges.php on line 71 and defined

```text
title: About
fields:
  toggle:
    label: Test
    type: toggle
```

**Comment by texnixe** [comment]
I think that has to do with the name of the field, I can reproduce this when I rename the name of the toggle field in a testkit.

**Comment by jenstornell** [comment]
I can confirm that changing the name did the trick after logging out and in again and re-saved the data.

I think it's strange that I can't use `toggle` as a key. Shouldn't I be able to use any key name I want (without special characters)?

Anyway, if the key `toggle` for some reason is protected, the docs should be changed instead:
https://getkirby.com/docs/cheatsheet/panel-fields/toggle

**Comment by huleos** [comment]
I just went through the same 🙄
How did you solve it @jenstornell ?

**Comment by texnixe** [comment]
@huleos: as mentioned above, if your field is called `toggle`, rename it to `mytoggle` or whatever. If you have another issue with the field, let us know.
