### ISSUE TITLE
Bug with URL field and validation

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby-v2/panel#1044]
Forum Thread : https://forum.getkirby.com/t/bug-in-panel-url-field/7498

Looks like this url `http://special---offer.com/` gets rejected by the url field.
Must be because of the triple dash in the url.

**Comment by jenstornell** [comment]
I just tested that url with a [html5 validator tool](http://www.456bereastreet.com/lab/html5-input-types/) and I can confirm that this url should be valid and submitted.

**Comment by lukasbestle** [comment]
Validating URLs is very very hard, see [this comment](https://github.com/getkirby/toolkit/blob/master/lib/v.php#L133). 😜 
Do you know a better way of validating URLs that we could use?

**Comment by manuelmoreale** [comment]
@lukasbestle I'm not an expert in regex but I found this one http://blog.mattheworiordan.com/post/13174566389/url-regular-expression-for-links-with-or-without and seems to work pretty well.

<img width="469" alt="screen shot 2017-05-29 at 8 52 23 am" src="https://cloud.githubusercontent.com/assets/1738077/26539334/2891183c-444c-11e7-891e-b410c610b006.png">

**Comment by lukasbestle** [comment]
Thanks. We'll definitely need to add a lot of unit tests for this though to make sure that all relevant types of URLs match. Otherwise we will probably break other strange types of URLs. I will keep this open, until then you can replace the regex on your Kirby installation as a temporary fix. :)

**Comment by distantnative** [comment]
@manuelmoreale - sadly that regex fails at least for

```
http://✪df.ws/123
```

which IS a valid URL.

**Comment by distantnative** [comment]
I managed to modify our existing regex to include the mentioned url as valid:

```
_^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9-]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/[^\s]*)?$_iu
```

However our source for our current regex (https://mathiasbynens.be/demo/url-regex) lists the following urls as invalid:

http://-a.b.co
http://a.b-.co

Those would be parsed as valid with this new regex. Are they actually valid by now or do we need to look further?

**Comment by lukasbestle** [comment]
See [RFC 1035, page 8](https://tools.ietf.org/html/rfc1035#page-8). Domain names must start with a letter and end with a letter or digit, which is why those URLs aren't valid.

Maybe we should use a proper parser that checks the URL character by character. RegExes aren't going to cut it.
But the question is if that's worth it. ;)

**Comment by distantnative** [comment]
I was mainly confused cause the HTML5 url form field validation let them pass. But looks like their validation is way less precise than our current.

And I agree, maybe it's worth to consider a much less strict regex instead of overdoing it.

**Comment by manuelmoreale** [comment]
> And I agree, maybe it's worth to consider a much less strict regex instead of overdoing it.
I personally quite like this approach

Domains these days are getting weirder and weirder and is gonna be a pain for you guys to keep up with the madness.
