### ISSUE TITLE
Filename sanitation works AFTER First SPACE or UNDERSCORE

### ISSUE THREAD

**Issue by imikekgd** [getkirby-v2/panel#1047]
During filename sanitation at uploading some cyrillic (as example) named files sanitation chowing everything UNTILL first SPACE or UNDERSCORE:

examples:

документ.docx -> .docx (leading red error in panel)
другой документ.docx -> _document.docx
_другой документ.docx -> _drugoj_document.docx

**Comment by lukasbestle** [comment]
We will look into this, but I can't guarantee if we will be able to fix this. We have had a lot of strange ASCII conversion issues and often didn't find out why it doesn't work. But we will try. :)

**Comment by distantnative** [comment]
I can't reproduce this. With the mentioned file names, I get correctly sanitised names after upload:
<img width="360" alt="screen shot 2017-06-18 at 08 28 17" src="https://user-images.githubusercontent.com/3788865/27258652-2e332dde-5400-11e7-9778-89e14e402632.png">

**Comment by imikekgd** [comment]
what's your php / kirby versions?
and do you setup locales additionally before using sanitation methods of
kirby somehow?

i'm getting same problem while using safeName in Kirby either basename just
in php. Really strange.

**Comment by distantnative** [comment]
PHP 5.6.10, Kirby newest version from the `develop` branch.
I have not set up any language/locales settings in the `config.php`.
What about you?

**Comment by bastianallgeier** [comment]
@imikekgd do you have the mb_string extension running on your server? That would be my best guess why such stuff goes wrong.
