### ISSUE TITLE
Customize Panel directory location

### ISSUE THREAD

**Issue by tillprochaska** [getkirby-v2/panel#1053]
Currently, the paths to most relevant directories are customizable – there’s no option to set the location of the Panel directory. It’d be great to see this in a future release.

‣ [Related post in the Kirby forum](https://forum.getkirby.com/t/custom-directory-structure-changing-location-of-the-panel-dir/7638)

**Comment by lukasbestle** [comment]
You can actually already *rename* the `panel` directory to whatever you want. The only requirement is that the Panel is in the root directory of your site. We won't be able to change this in Kirby 2, but we have plans for the future.
