### ISSUE TITLE
Be able to add field assets conditionally

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#1058]
Now it looks like this in a field:

```php
static public $assets = array(
  'css' => array('style.min.css'),
  'js' => array('script.min.js'),
);
```

**Related:** https://forum.getkirby.com/t/set-field-asset-with---construct/7005

As far as I can tell there is no way to add assets conditionally. Let's say it make sense to do this:

```php
if(c::get('debug')) {
  static public $assets = array(
    'css' => array('style.css'),
    'js' => array('script.js'),
  );
} else {
  static public $assets = array(
    'css' => array('style.min.css'),
    'js' => array('script.min.js'),
  );
}
```

>syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)

or...

```php
static public $assets = array(
  'css' => array('style.' . c::get('my.plugin.color') . '.css'),
  'js' => array('script.js'),
);
```

>Constant expression contains invalid operations

Because it's set as static variable, we can't control it. Maybe it could be used as a static asset (like it is now) OR be overwritten by the `__contruct` somehow?

**Comment by lukasbestle** [comment]
Erm, what about this?

```php
class MyField extends BaseField {
  static public $assets;
}

if(c::get('debug')) {
  MyField::$assets = array(
    'css' => array('style.css'),
    'js' => array('script.js'),
  );
} else {
  MyField::$assets = array(
    'css' => array('style.min.css'),
    'js' => array('script.min.js'),
  );
}
```

**Comment by jenstornell** [comment]
Thanks, that works brilliantly to my current project. I will probably add it as a Kirby Secret. :)

About the issue, do you think this is the solution we should use in the future?

- It's not very straight forward and easy to figure out, I think.
- The variable is set outside the class. It's like something fell out of the box.

So I still hope for some improvement in the panel core in the long run.

**Comment by lukasbestle** [comment]
I agree that this shouldn't be used in production plugins and fields.

My recommendation: Always use minified assets. It doesn't make sense to have this conditional check only for local field development. You can always use source maps for debugging.

**Comment by jenstornell** [comment]
Thanks for the suggestion about source maps.

About the issue. If we need a more dynamic css, like using a color set in the config.php, you think it should be done like the code below, outside the class? Or do you think there is a way in the future to make it a part of the class?

```php
class MyField extends BaseField {
  static public $assets;
}

MyField::$assets = array(
  'css' => array('style.' . c::get('my.plugin.color') . '.css'),
  'js' => array('script.js'),
);
```

If you think it would be nicer to have it inside the class, reopen this issue?
