### ISSUE TITLE
Manual default sorting of pages in pages view does not seem to work reliably when the internal Panel sort order is set to some field

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1066]
See this forum post: https://forum.getkirby.com/t/sorting-subpages-visually-sorted-in-panel-but-not-re-ordered/7806

**Comment by lukasbestle** [comment]
Shouldn't we maybe disable sorting in the Panel all-together? It doesn't make sense to sort pages manually if they are sorted by some field.

Possible solution: Enforce `num: zero` if any kind of sorting is used.

**Comment by texnixe** [comment]
The problem here is that some sort of sorting like sorting by date or alpha does not only affect the internal panel sort order but also the file system based sorting order, whereas sorting by a particular field with default (01, 02 etc) sorting enabled does still allow manual sorting but does not work as expected, i.e. manual sorting via the sidebar options does work as expected but in the pages view it doesn't. 

I'm not so sure that enforcing `num: zero`makes sense if you sort by date or title, for example.

**Comment by lukasbestle** [comment]
But how is manual sorting supposed to work if automatic sorting is enforced in the Panel? If you sort manually, the pages will always jump back to their automatically sorted order. So manual sorting is always going to result in unexpected behavior and strange sort order jumping.

**Comment by texnixe** [comment]
I agree that this is a problem. It is no problem if we select a sorting number via the sidebar options, but dragging and dropping in pages view is confusing, indeed. Maybe the internal Panel sort order should be deactivated in the Pages View, then, rather then disabling manual sorting? I'm not 100% sure, but I don't think pages shouldn't be manually sortable if their numbering scheme is set to default and they are set to sorting by title. Somehow the num and sort options seem a bit contradictory.

**Comment by lukasbestle** [comment]
That's a good alternative as well. Basically we would just display the pages in the order of their sorting numbers in all cases, even if manual sorting/flipping is enabled.

**Comment by jenstornell** [comment]
+1 for always order by the manual sort order in this view. If the pages are not manually sorted by the user I guess they will be sorted by filename, which is fine.
