### ISSUE TITLE
Support for webp in image field

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1068]
See https://forum.getkirby.com/t/webp-and-image-field/7841

**Comment by jenstornell** [comment]
When it has good browser support I agree but so far it has not. Firefox, Safari and Edge is missing.

**Comment by texnixe** [comment]
@jenstornell As I already mentioned in the forum, the fact that not all browsers support a feature, does not mean that the feature should not be used for those browsers that support it. Nobody forces you to use .webp if you don't want to so I don't see any reason to disagree?

**Comment by JimmyRittenborg** [comment]
Since WEBP is supported in 73.7% open browsers at a current global level http://caniuse.com/#feat=webp and taking into account that images being the single worst bottleneck for web performance, support for this image format should be highly considered.

**Comment by jenstornell** [comment]
It's a format made by Google. The only browser that supports except Google Chrome is Opera which does not have a big market.

Maybe we are going to add new formats anyway? Except for Google Webp, why not also support Microsoft jpeg XR and Mozilla Apng? These also have mixed browser support.

**Comment by klloe** [comment]
> not have a big market.

Pretty much all the latest android devices support webp using the builtin browser or chrome. That's a huge market!
