### ISSUE TITLE
'parent' option for showing preview-links in blueprints does not work within options

### ISSUE THREAD

**Issue by wottpal** [getkirby-v2/panel#1084]
Hey currently I can set `preview` in my blueprints to `false` to disable showing a preview-link in the panel when it doesn't make sense (esp. when there is no page). But often I want to preview the (grand-)parent in which the currently edited page is displayed as an item/image or whatever. Does this make sense for your as well?

```yaml
options:
  preview: parent  #or 'grandparent'
```

In the sidebar of the page in the panel could then be displayed something like "Open {{name_of_parent}}" instead of the generic term "page".

Dennis

**Comment by medienbaecker** [comment]
Does that not work for you?

https://getkirby.com/docs/panel/blueprints/page-settings#page-preview

**Comment by wottpal** [comment]
🙈🙊🙉 
Nevermind! Sometimes I'm totally blind while reading documentation.

But: `parent` doesn't seem to work when `preview` is under `options` but it should, right? At least `false` works in that case.

**Comment by texnixe** [comment]
That's right, it doesn't work but imo it should. Does work as a separate setting, though.

**Comment by jenstornell** [comment]
@wottpal I made a plugin for this problem:
https://github.com/jenstornell/previewer

In the long run I think that this idea would solve a lot of things, this included:
https://github.com/getkirby/panel/issues/979

But as @texnixe said, it might be a bug in this case.

**Comment by texnixe** [comment]
Maybe the options only refer to the UI and this is not even a bug. But it is at least confusing.
