### ISSUE TITLE
Apply file sorting across all languages

### ISSUE THREAD

**Issue by kraftner** [getkirby-v2/panel#1087]
Currently you can [enable file sorting](https://getkirby.com/docs/panel/blueprints/file-settings#sortable-files):
```
…
files:
    sortable: true
…
```
This is stored as file meta, but only for the currently edited language. So if you change the order in one language the old sort order stays the same in all other languages.
It would be great if one could apply this sorting to all languages, [just like you can do with form fields](https://getkirby.com/docs/panel/blueprints/form-fields#prevent-field-values-in-non-default-languages).

Maybe something like:
```
…
files:
    sortable: translate
…
```

**Comment by texnixe** [comment]
Makes totally sense, in most cases, I guess in most cases you won't want to have a different sort order in other languages.

**Comment by texnixe** [comment]
As a workaround while there is no such feature, you could probably use a hook to keep the files in sync.

**Comment by kraftner** [comment]
I thought about and tried that approach, but I didn't really succeed. Do you have any hints on how I might approach that? I think I'd also run into #1006, right?

**Comment by texnixe** [comment]
True, that issue will likely get in the way.
