### ISSUE TITLE
Logging in to the Panel is not possible with a user role defined in a plugin…

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1088]
… if other roles are already present in `/site/roles`.

**Comment by samnabi** [comment]
I ran into this issue even when there are no roles present in `/site/roles`. If there are multiple roles defined by a plugin (using `$kirby->set('role', ...`), none of them can log in to the panel.

**Comment by lukasbestle** [comment]
Hm, I can't find the origin of this bug.

The plugin role is loaded correctly in the Panel and the user object is created. The login succeeds but then the user is suddenly logged out again in the same request. But that only happens with users with a role that is defined via the registry.

This is unfortunately one of those bugs that I can't trace back. Could someone else from the team take a look at this?
