### ISSUE TITLE
Image field breaks $oldPage in hooks

### ISSUE THREAD

**Issue by bvdputte** [getkirby-v2/panel#1094]
When you
- have a multilingual setup
- use the image field
- have an image selected in that image field

`$oldPage` in hooks is broken.

Also see [topic in Kirby forum](https://forum.getkirby.com/t/oldpage-in-hooks-doesnt-return-previous-version-of-the-page/8344/5).

**Comment by bvdputte** [comment]
On [line 422](https://github.com/getkirby/panel/blob/370e9767766c2d9404bcbaf0fd1f7922d9458bd1/app/src/panel/models/page.php#L422) all is as expected, nothing happens with $old and on [line 433](https://github.com/getkirby/panel/blob/370e9767766c2d9404bcbaf0fd1f7922d9458bd1/app/src/panel/models/page.php#L433) it has been changed to the new values. I really don't understand how this is possible :-(

Any chance you can look into this @lukasbestle ? Or help me find a workaround in the meantime. Thx!

**Comment by lukasbestle** [comment]
That's a very strange bug:

The only special thing about the Image field is that it [accesses the `$page->images()` object](https://github.com/getkirby/panel/blob/2.5.5/app/fields/image/image.php#L74).
If I replace that line and [this second line](https://github.com/getkirby/panel/blob/2.5.5/app/fields/image/image.php#L19) with something like this (faking the image objects):

```
$images = [
  new Obj(['filename' => 'test', 'extension' => 'jpg', 'url' => 'http://placekitten.com/75/75']),
  new Obj(['filename' => 'test2', 'extension' => 'jpg', 'url' => 'http://placekitten.com/75/75'])
];
```

and removing the thumb stuff from the field, it all works totally fine. So as soon as a field accesses any sub-object of `$page` object, the `$oldPage` is messed up (even with my fixes from #1025).

Even stranger is that it only affects multilanguage installations. I have *absolutely no clue* why this only happens there. The custom multilang classes don't do anything particularly special with file objects.

@distantnative, could you please take a second look at this? I have no idea where to search anymore.

**Comment by lukasbestle** [comment]
Nico has taken a look at this but couldn't find the issue either. I will take a second look at it for 2.5.7, but can't promise anything. :(

**Comment by bvdputte** [comment]
Oh darn. That's not good :-(

**Comment by lukasbestle** [comment]
I'm really sorry, but I can't find the origin of this issue.

If anyone of you has more luck debugging this and finds new information regarding this (adding to what I found out above), I'd be more than happy to help with debugging this further and finding the actual issue.

**Comment by bvdputte** [comment]
This is bad...

Basically this renders _comparing pages via hooks_ useless when in above described scenario (which isn't really exotic — quasi all my sites are multilingual and use the image field).

**Comment by lukasbestle** [comment]
Well, I fully agree. But as I said we currently can't do anything about this. Nico and I have thrown a lot of time at this issue as bugs like this absolutely shouldn't exist.
I'm pretty sure though that this will improve with Kirby 3 as it is a complete rewrite and shouldn't carry over this kind of bugs. :)
