### ISSUE TITLE
With pages: false setting in site.yml, hide: true page setting does not work.

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1107]
While it is arguable that setting pages to false in site.yml makes sense, we could nevertheless hide a hidden first level page.

(Although, from a logical point of view, when pages is set to false in site.yml, no pages should show up in the pages widget, like no subpages are shown in the sidebar with subpages set to false).

https://forum.getkirby.com/t/cant-hide-page-in-panel/6925/16

**Comment by luxlogica** [comment]
A very common use-case for me is sites that have a set configuration and number of top-level pages, which should not be changed. For instance: a site that has a landing page, and a blog section, an error page, and a 'search results' page. Although the user should be able to add Article pages to the blog, or perhaps sub-pages to the landing page, at the top-level we don't want the user to be able to change anything - neither delete nor add any pages. In my experience, dealing with a lot of small business sites, this is indeed a very common setup.

Now, I came across the trick of using a `pages: false` setting in the _'site.yml'_ blueprint by accident, and was surprised to see that it did *exactly* what I needed. The alternative to that was to change various settings in *every other* blueprint of the site - a much more laborious and error-prone task. 

So, if this was an "unintended feature", could we make it an _intended_ one? ;-)
