### ISSUE TITLE
Session and data is lost when changing template

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#1109]
https://forum.getkirby.com/t/panel-templatechange-hook/8746

**At the moment it works like this:**

1. I change content in a field in the panel.
1. I refresh the page without save and get "You have unsaved changes" (correct).
1. I change template, still without saving.
1. The "You have unsaved changes" is gone. I guess the session is lost.
1. The unsaved changes are gone and reverted to the latest save.

**To me a correct flow would be:**

1. I change content in a field in the panel.
1. I refresh the page without save and get "You have unsaved changes" (correct).
1. I change template, still without saving.
1. I still see the "You have unsaved changes".
1. I still see my unsaved changes and can save them if I want.

Maybe it's not important to fix today, but for the future I think it can be good to implement.

**Comment by texnixe** [comment]
I'm not so sure I would want such a workflow. If I change template after I have made changes, a lot of that content might be useless afterwards. 

I think it would be better if the Panel would check if there are unsaved changes at the moment when the user wants to make changes and warn him to save these changes.
