### ISSUE TITLE
Page option `status: false` disallows sorting of visible pages

### ISSUE THREAD

**Issue by zakgreene** [getkirby-v2/panel#1113]
I noticed I couldn't reorder visible pages in the Panel and couldn't figure out why. This is my first time using Kirby since 2.5 was released. Eventually, by process of elimination I discovered it was the `status: false` option in the default Blueprints in the Starterkit. I think if `status` is going to affect sortability in addition to visiblity, it should be documented, but ideally sortability would be a separate option.

**Comment by lukasbestle** [comment]
I see your point that this should be a separate option and also a separate permission.
However sorting and visibility are currently very intertwined. A page is currently set to `visible` by sorting it.

Kirby 3 will have better handling for this. I'm adding this to the v3 milestone – we will verify that this works properly in Kirby 3. :)

**Comment by zakgreene** [comment]
Cool, thanks!
