### ISSUE TITLE
Invalid jpg image causes Panel crash: Upgrade SimpleImage

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1122]
https://forum.getkirby.com/t/invalid-jpeg-marker-causes-panel-to-crash/9072

**Comment by lukasbestle** [comment]
Needs an example file for debugging.

**Comment by anteante** [comment]
@lukasbestle here are a couple of files that caused a crash of the panel in my system: [archiv.zip](https://github.com/getkirby/panel/files/1511569/archiv.zip)

**Comment by lukasbestle** [comment]
Thank you for the super quick reply. However I can't get the Panel to crash with any of those images. Could you please tell me exactly which steps were needed to reproduce this?

**Comment by anteante** [comment]
Sure, no problem – I can send you a zip archive of the project if that helps. Just let me know where I should send it to.

**Comment by lukasbestle** [comment]
I'm not sure that I will be able to reproduce this in your project if I can't reproduce this in the starterkit, but we should at least try that. :)

Please send the files to lukas at <Kirby's domain> (removed for spam protection). Thanks in advance!

**Comment by anteante** [comment]
As a matter of fact, I **can** reproduce it in the starterkit –  to some degree. When I add the three files mentioned to a project folder, the breadcrumb navigation in the panel changes to 'Dashboard > Error' – it's not quite a total crash as I am experiencing it in my particular project, but something seems to be dodgy.

**Comment by lukasbestle** [comment]
As I said, I can't reproduce this in the starterkit. Could you please send me your project?

**Comment by lukasbestle** [comment]
I have received the files from @anteante and will look into this issue for 2.5.9.

**Comment by lukasbestle** [comment]
I couldn't reproduce the issue but have updated the `SimpleImage` library. The new version contains a fix that should at least fail gracefully and not completely break the Panel.

**Comment by lukasbestle** [comment]
I had to revert the `SimpleImage` upgrade for now to restore compatibility with plugins. A breaking change like this can't be in a patch release.

We will upgrade our vendor dependencies with Kirby 3.

**Comment by eighthday** [comment]
I have the same exact problem, tried 2.5.9 - RC1 to no avail. Certain images just crash the panel, with no error message. While we accept the image is the issue (although opens fine in photoshop, can be uploaded to other cms  etc..) the client can not recover the page. The only way to fix is to delete the image via sftp and the page options come back.  We just need an error message and the panel to reject the image.

**Comment by lukasbestle** [comment]
As I wrote, I had to revert the change that introduced the error message because of compatibility issues.

What you could try is to [switch to ImageMagick](https://getkirby.com/docs/cheatsheet/options/thumbs-driver) as your thumb driver. Maybe those "broken" images are accepted by ImageMagick while not being accepted by GDLib.
