### ISSUE TITLE
Error on Panel when editing a type Structure on a multilanguage setup

### ISSUE THREAD

**Issue by isaactopo** [getkirby-v2/panel#1123]
If you are on a multilanguage setup, 

1. You fill a type structure from the panel on the default language. and save.
2. Go to another language and try to Edit some of the type structure you have added previously on the default language
3. You get this error:

> Error
> The item could not be found

![captura de pantalla 2017-11-23 a las 18 04 54](https://user-images.githubusercontent.com/4568596/33183676-1999ac4a-d079-11e7-82c0-5e5f8bb5279e.png)

If you save the page and then edit is all ok, but i think it colud be better to not throw this error, get the default values from the default language and let the user edit and save without an error.

**Comment by sen-zo** [comment]
Also: After saving the second language, you can edit it. But if you go back to the default language and save it, the editing on the second language will be broken again.

This also breaks the Builder-Plugin: [https://github.com/TimOetting/kirby-builder/issues/54](https://github.com/TimOetting/kirby-builder/issues/54)

**Comment by maltewassermann** [comment]
@bastianallgeier you can fix it by using the current language:

https://github.com/getkirby/panel/blob/9c54ef6cfe68bfa9e1c618cbf42eeaf222f1d833/app/src/panel/structure/store.php#L73

`$fileDefL     = $this->structure->model()->textfile(null, site()->language()->code());`

**Comment by saltandbits** [comment]
Hey, I'm afraid I still have this error, been trying to isolate the problem and this is how I get it; when I place an empty image field after a structure field in the panel, change the language 3 or 4 times and then try to edit the structure I get the above mentioned error. Tried this on an clean install of Kirby.
