### ISSUE TITLE
User can't log in when user role is missing from account file

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1134]
Makes sense, but maybe show an error?
https://forum.getkirby.com/t/login-to-panel-issue/9529/15?u=texnixe

**Comment by lukasbestle** [comment]
I'm pretty sure that's because we introduced a new "nobody" role a while back for security reasons. And I think that this behavior makes sense.

But you are right: There should probably a message like "you don't have permission to access the Panel".
