### ISSUE TITLE
Hitting the "page end" button on the keyboard triggers page deletion

### ISSUE THREAD

**Issue by gerricom** [getkirby-v2/panel#1136]
I'm using the latest Firefox (58 at the moment). When I'm working in the panel and I want to scroll down to the bottom of the page, I'd like to use the "scroll to page end" button in my Mac keyboard. Nowadays this triggers the "do you want to delete this page"-modal in the panel. I'm quite sure, this is not wanted und maybe you are listening for the wrong key in js?

**Comment by bastianallgeier** [comment]
I finally wanted to solve this, but I can't reproduce it on Firefox 61. Do you still have this issue in the latest Firefox version?

**Comment by gerricom** [comment]
Yes, I can still reproduce this in Firefox, Chrome and Safari.

**Comment by texnixe** [comment]
Yes, if you press fn+right arrow, I can reproduce this in Safari.
