### ISSUE TITLE
Adding an image field to users throws an error

### ISSUE THREAD

**Issue by StevenVerbiest** [getkirby-v2/panel#1143]
I have defined a default user blueprint with some extra fields as described in the [docs](https://getkirby.com/docs/panel/users).

But when I try to add an image field:

```
customimage:
  label: Custom image field
  type: image
``` 
The following error gets thrown:
`Method ImageField::__toString() must not throw an exception, caught Error: Call to a member function image() on null`

Not sure if I'm doing something wrong?

**Comment by texnixe** [comment]
You can only upload user avatars but not additional images for users.
