### ISSUE TITLE
Multilanguage non-required dropdown/select field issue

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/panel#1149]
I'm using select field on files picker with multilanguage TR and EN (Default lang is TR)

My field syntax:

    fulltextpdf:
        label: Full Text PDF
        type: select
        options: query
        translate: optional // for each language data is different
        query:
            fetch: files
            value: '{{filename}}'
            text: '{{filename}}'
        required: false

Error on following processes on `fulltextpdf ` field:

1. TR field is selected
2. Switch language to EN
3. EN field blank to selected
4. Saving error as "Please fill in all fields correctly"

I found the temp solution to save with following processes on `fulltextpdf ` field:

1. TR field is leave blank and save
2. Switch language to EN
3. EN field select and save
4. Switch language to TR
5. TR field select and save

Tested on Kirby 2.5.5 and 2.5.12 versions.

Discussion on Kirby Forum: 
https://forum.getkirby.com/t/multilanguage-dropdown-select-non-required-issue/10987

**Comment by lukasbestle** [comment]
That indeed looks like a bug. For Kirby 3 we are currently implementing the multilang code from scratch, so it most likely won't have this issue.
