### ISSUE TITLE
[idea] Quick add panel field for pages / taxonomies, like in Wordpress

### ISSUE THREAD

**Issue by maximelebreton** [getkirby-v2/panel#1151]
I think that Kirby needs a **Quick add** panel field feature, when we want to create pages or taxonomies without leaving the current page, like the Wordpress quick add category feature.

__________  

![kirby2](https://user-images.githubusercontent.com/1072425/45854062-4b656a80-bd49-11e8-9f8c-80a4d12cd087.gif)
In **Kirby 2**, if you have a select field based on pages, and you want to create a new one from here, it's not possible without leaving the current page...

___________  

![quick-add-wordpress](https://user-images.githubusercontent.com/1072425/45854065-502a1e80-bd49-11e8-9c32-e3589ff4b254.gif)
In **Wordpress**, it's possible to quick create a new category without leaving the current page

**Comment by maximelebreton** [comment]
Thank you, but sadly it miss an autocomplete feature.

Any plans to implement this?

**Comment by texnixe** [comment]
No, I don't have any plans to do that and  we will not build such new features into K2.
