### ISSUE TITLE
Only show field if …

### ISSUE THREAD

**Issue by ziburski** [getkirby-v2/panel#121]
It would be great to hide fields in the panel on certain conditions.

I might have a "Show Event Info" check-button, and several fields for entering event related info. However, these fields are only needed if I actually want to show event information. So these fields should be hidden in the panel until I check "Show Event Info".

That would obviously be a very basic problem, but I guess there are a lot of possibilities with general conditions for fields.

**Comment by vicegold** [comment]
:+1:

**Comment by texnixe** [comment]
+1

**Comment by DanielRivers** [comment]
I have written a plugin which I think will make this easy.  I will test in my panel and report back :)

**Comment by DanielRivers** [comment]
@ziburski This what you after? http://recordit.co/TNaYMG5HXY

**Comment by vicegold** [comment]
@DanielRivers that's absolutey the thing we're asking for! Great work!

**Comment by DanielRivers** [comment]
@vicegold Great, I have sent team a message on twitter.

Its simple to work with, added it to blueprints.  The example in the video works with simply adding the following to the relevant fields.  Panel does the rest.

visible: attachevent=true

Supports equals, not equals and regular expressions

**Comment by byybora** [comment]
Why not exists visibly feature on Kirby 2.1?

**Comment by louiswalch** [comment]
+1

**Comment by hotovec** [comment]
+1

**Comment by Tapefabrik** [comment]
@DanielRivers : was your feature recognized by the team? If not, why? Just curious because right now we are thinking about setting up a plugin around that topic.

**Comment by bastianallgeier** [comment]
Hey, it was totally recognized and I even started building it in, but it came at about the same time we started working on permissions and some other features and it felt that I should refactor the panel source first before adding more such features. You can read a bit more about it here: http://forum.getkirby.com/t/behind-the-scenes/1778

That's why this and some other stuff is on hold, but definitely still on the list.

**Comment by rbnschlz** [comment]
Any new plans to implement such a feature?

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by illycz** [comment]
(y)

**Comment by Thiousi** [comment]
I'd love to see this coming out soon! If there's anything we can do to help push it out for 2.3.1 it'd be great :)

**Comment by Sija** [comment]
👍

**Comment by jenstornell** [comment]
I hope 2.3.1 will be a bug fix release only.

**Comment by DanielRivers** [comment]
I am ready to work into latest panel when @bastianallgeier is ready.

**Comment by jenstornell** [comment]
Related. Conditional fields with a plugin called Fieldtoggle:

https://forum.getkirby.com/t/kirby-fieldtoggle/5010
