### ISSUE TITLE
idea: convert to RGB upon upload

### ISSUE THREAD

**Issue by skifreak** [getkirby-v2/panel#168]
I'm not sure how easy this would be to implement ~ but ~ it would be great if all images uploaded through the panel were converted to RGB if they were in CMYK colorspace. I have a magazine as a current client, and most of their material is set for print and not for web. I gave them a Photoshop action so they can convert all of their content themselves - but they keep forgetting to do so, and loading times are slow.

Just a thought!

**Comment by servicethinker** [comment]
+1. Good point!

**Comment by skifreak** [comment]
Another thought about this,
It would be great if images were also automatically converted to sRGB - I have had photographer friends who are baffled when the file on their desktop (in Adobe RGB) looks drastically different when online.

**Comment by seehat** [comment]
I posted a solution for this in the Kirby Forum: http://forum.getkirby.com/t/srgb-conversion-and-resize-upon-upload-of-images/402
