### ISSUE TITLE
Question: Possible to set sidebar titles ('Sites', 'Files', …) in blueprints?

### ISSUE THREAD

**Issue by jakobploens** [getkirby-v2/panel#248]
I'd really love the feature of setting the sidebar title of Sites and Files in blueprints. Would make it much more easier for clients to know what they are editing if the title would be customizable, for example 'Products', 'Entries', 'News' or whatever, and everything related to this site would adapt the title – Visible and Invisible Products instead of Visible/Invisible sites for example.

Would make Kirby 2 even more awesome. <3

**Comment by distantnative** [comment]
+1

**Comment by rooraggio** [comment]
+1

**Comment by lukasbestle** [comment]
Also see [this topic in the forum](https://forum.getkirby.com/t/option-to-call-subpages-something-else-instead-of-pages-for-example-posts/3067?u=lukasbestle).

**Comment by texnixe** [comment]
+1

**Comment by jenstornell** [comment]
Good idea. Just make it optional,  not forced.

**Comment by lukehatfield** [comment]
+1

**Comment by samnabi** [comment]
+1

**Comment by medienbaecker** [comment]
+1

**Comment by rhawbert** [comment]
+1

**Comment by mtclmn** [comment]
Has anyone figured out how to do this manually until it is integrated?

**Comment by distantnative** [comment]
@mtclmn: To edit the core manually, it's not that trivial. You would need to edit the blueprint model to define how to specify the sidebar labels, maybe even create a new blueprint subclass for this. Then you'd need also to edit the sidebar model as well as the several sidebar snippets.

All these changes over multiple files would pretty much guarantee that your manual implementation would break with the next update.

**Comment by JimmyRittenborg** [comment]
+1

**Comment by texnixe** [comment]
See this [discussion in the forum](https://forum.getkirby.com/t/my-panel-wishlist/50/65).

**Comment by JimmyRittenborg** [comment]
Wow @texnixe, of cause ..didn't really thought about that one! 😆

**Comment by lukasbestle** [comment]
This discussion has now been moved into its [separate topic](https://forum.getkirby.com/t/make-title-for-pages-in-the-panel-translatable/3286/24).
