### ISSUE TITLE
Enhance hiding options for pages and files

### ISSUE THREAD

**Issue by RHansmann** [getkirby-v2/panel#250]
Currently for both  blueprint groups "pages" and "fields" only parameter "hide: true" or "hide: false" can be specicified. Specifying a file name for field hiding is treated as "hide : true".

It makes sense, that additional to the values "true" and "false" also filenames can be specified:

for "pages" it should be a pattern of page and/or template names, i.e: article_test?
for "files" it should be a file pattern, i.e:  test_.jp?g 
(\* = means any character of any length, ? = can be any single character including "empty" to catch i. e. both jpg types: "jpg" and "jpeg")

This prevents an author/editor to modify all subpages and files. Instead he can modify only visible pages and files.

**Comment by distantnative** [comment]
Tried a solution that accepts regular expressions (`*.jpg` will throw error, but `.*.jpg` works). Right now it tests on page uid for subpages and filename for files. I'm not sure how I'd implement page uid and/or template.

**Comment by afbora** [comment]
+1
