### ISSUE TITLE
Request: Field visibility dependant on other field values

### ISSUE THREAD

**Issue by crispconcepts** [getkirby-v2/panel#262]
I perused the open enhancement requests and didn't see this, but if it's a duplicate I apologize.

Is there any plan to make certain fields dependent on the selection in previous fields? I saw another request for field grouping / collapsing.. but that's not quite what I'm looking for.

My real life example is that I'm creating a grid system in kirby using neat. It will generate the grids using pages, rather than creating kirbytext markup for grids. The grid's span value can be Normal, Full Width or Table.

If the user selects a table span, I'd like the columns added to have a property for valign. If the parent is Normal or Full Width, the valign property isn't necessary and rather than having to add a notation that "this field is only used for table grids", it'd be nice if it just didn't show up.

I could achieve this by creating blueprints for each type of grid, rather than by using a span property in the single grid blueprint.. but this removes the ability for the user to change the grid type on the fly from within the panel.

My specific scenario would require the field dependencies to span multiple blueprints rather than a single blueprint.. But even with support in a single blueprint, I could add the valign property to the grid rather than allowing each column to have it's own alignment set.

**Comment by vicegold** [comment]
:+1:
