### ISSUE TITLE
Resize/crop images

### ISSUE THREAD

**Issue by Hofstede** [getkirby-v2/panel#311]
Would be nice to be able to have the option for clients to resize and crop images in the files view (like in wordpress).

**Comment by byybora** [comment]
+1 the feature! Changable crop position as top, left, right, bottom that would be great!

**Comment by ian-cox** [comment]
+1 I'm also looking for a solution to this problem.

**Comment by tijngoessaert** [comment]
+1

**Comment by tijngoessaert** [comment]
+1

**Comment by jdvivar** [comment]
+1

**Comment by seehat** [comment]
I've found some links, describing the process of client side resizing images before upload, to 

- reduce upload time and 
- allow the user to upload original files, without the use to resize them, which is partly difficult to explain to clients.

https://gist.github.com/mfyz/10198229
https://github.com/joelvardy/javascript-image-upload
https://hacks.mozilla.org/2011/01/how-to-develop-a-html5-image-uploader/
https://davidwalsh.name/resize-image-canvas
