### ISSUE TITLE
If clauses for structure filed labels

### ISSUE THREAD

**Issue by tweh** [getkirby-v2/panel#324]
I don’t know if it’s possible but it would be handy to have some basic `if` clauses for the structure fields. For example I build a calendars which’s events are saved in a structured fields and it would be nice to show the end time only if it is different form the start time or to hide the label if a field is empty.

**Comment by benseitz** [comment]
:+1:

**Comment by servicethinker** [comment]
+1

**Comment by distantnative** [comment]
Could be solved with #747.
