### ISSUE TITLE
Idea: Kirby Clipboard

### ISSUE THREAD

**Issue by jakobploens** [getkirby-v2/panel#342]
I have no idea how to implement this in a nice and easy to use way, but here's my idea. It came to my mind when restructuring and rewriting lots of content with the panel. Wouldn't it be nice to have a kirby-intern clipboard with multiple clips, where you could copy texts to and paste them later on a new site? Just the text, no field types, validation or anything. I also don't know if this would be a often-used feature, and therefore if the time is really worth it, but maybe one could think about it some minutes… I think this would also be a really nice feature for clients who work only (and often) with the panel, not with the FTP.

What do you think about it?

**Comment by lukasbestle** [comment]
That's a great idea, also for storing often-used text snippets.
I personally don't think that this should be part of the core though. Maybe we can find a way to implement such a system as a plugin for the Panel.

**Comment by jakobploens** [comment]
Yes, maybe that's a better way.

I also thought about tabs or something similar, but that would break the whole easy-to-use pattern I think…

**Comment by lukasbestle** [comment]
What about some kind of sidebar that slides out when not needed?

**Comment by jakobploens** [comment]
Yeah, that might be the right way!

**Comment by servicethinker** [comment]
I think something like [Yoink](http://eternalstorms.at/yoink/Yoink_-_Draggings_a_drag_no_more/) could also easily help - just drag and drop into the clipboard area in Kirby and insert with the same way into the new content.
