### ISSUE TITLE
Support rich, multiline figure captions in Markdown/Kirbytext

### ISSUE THREAD

**Issue by jaydenseric** [getkirby-v2/panel#361]
I have been struggling to find an elegant way to allow my clients to create figures (image or video) with rich, multiline figure captions within page content.

This is probably a common desire, since a lot of my Kirby projects are portfolios showcasing artworks which need to contain a lot of information in the captions about the title, date, medium, etc. [Example](http://jakestollery.com/works/ContemporaryConvergance).

`figcaptions` are supposed to be [able to contain flow content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) such as paragraphs and lists to describe the figure.

What is the best way to facilitate figures like this selectively within page content?
## Non-solutions:
1. Ordinary [page images with metadata files](http://getkirby.com/docs/content/media#adding-meta-data-to-your-files), looped in the page’s template to create a gallery. Not a solution because my clients need to be able to place artwork figures anywhere within the content of their page, not all looped together at the end. Also, not every image should appear in the content; some are for the page’s open graph image or act as thumbnail in navigation menus on other pages.
2. Use an extended Markdown compiler that supports figure and figcaption. Syntax discussion [here](https://github.com/michelf/php-markdown/wiki/HTML5-update). [PHP Markdown Extra Extended](https://github.com/egil/php-markdown-extra-extended#support-for-figure-and-figcaption-tags) seems to be a popular implementation. It’s not clear the new syntax supports multiline figcaptions, and I have not yet attempted to add this compiler to Kirby.
3. Use [custom Kirbytext tags](http://getkirby.com/docs/advanced/kirbytext). [Example gist](https://gist.github.com/bastianallgeier/2924148). I don’t think there is a way to add multiline markdown as a figcaption parameter to a Kirbytext tag.
## Current solutions:
1. Use drag and drop functionality of [Structure fields](http://getkirby.com/docs/cheatsheet/panel-fields/structure) to manage page content, instead of a large textarea with Kirbytext. Problem is, structure fields only contain one type of item. You can’t add a few “figure” types, then some “text” types and drag and drop them around as page sections. You have to make one generic type, with both “content” and “caption” textareas. Use the “caption” field for the template to convert that item into a figure, otherwise dump the “content” field out as ordinary Kirbytext. This is undesirable because you have to explain to the user how it works and it is more cumbersome than one large, free-flowing Kirbytext content field.
2. Combine a custom Kirbytext tag for insert a particular figure by ID from within a list managed in a Structure field. This allows figures to be populated using intuitive and specific fields, and placement can happen anywhere in the pages content Kirbytext. Another benefit is that this figure support can be applied to existing pages with content without significant refactoring or content re-entry. Downside: Managing the content in two places; linking to figures manually in the content text is annoying and fragile. What if you change a figure ID? You then need to do a manual find-and-replace thought the Kirybtext.

**Comment by jaydenseric** [comment]
On second thoughts, this issue may be more relevant to the Kirby core repo.

**Comment by lukasbestle** [comment]
Another pretty clean solution: Add the image metadata directly to the image file (like in your non-solution 1) and create a custom Kirbytext tag that gets passed the image file name (like the default `image` tag), fetches the image metadata directly from the image and builds HTML code like you want it to be.

Downside: The client won't be able to arrange the image information manually per appearance of the image, but you could add an option to the tag that allows for several distinct "caption styles" (which is actually even cleaner and more manageable). The tag could also check which metadata fields are set and decide which representation to use automatically.

**Comment by jaydenseric** [comment]
@lukasbestle Thanks for the suggestion, I have actually begun developing exactly this. The bummer is this only allows you to display files as figures, we need to also handle video embeds from Youtube, etc.

I am thinking some conditional logic for the custom Kirbytext tag. `(figure: filename.jpg)` would be recognised as a page file and the caption would be based of the file's  `caption` metadata field. `(figure: https://www.youtube.com/embed/dQw4w9WgXcQ)` would be recognised as an embed URL, the page's `videos` structure field will be searched for an item matching that URL and the `caption` field will be retrieved from that.

This is not very elegant for a user, having to click into all these different windows to add captions in different ways for each figure type, but it should work.

**Comment by lukasbestle** [comment]
Another solution (that would require a change to the Panel code) would be some kind of "metadata-only file".
The client would add a new "resource", which consists of the link and the caption. It's just like a file, but without an actual file being uploaded.

This way, both types of embeddable content would be stored in the same way next to each other. The video could be referenced by the resource (or "file") name.

**Comment by jaydenseric** [comment]
Another hack option:

```
(figure: start)
	(image: sloth-climbing-tree.jpg alt: A sloth climbing a tree)
	(youtube: https://www.youtube.com/watch?v=zNnWhQPQRFQ)
	(caption: start)
		Sloths are *great* climbers.
	
		**Media:** Joe Bloggs
	(caption: end)
(figure: end)
```

It's unfortunate Kirbytext automatically wraps figure tags around images and video, even if they don't have captions.

**Comment by jaydenseric** [comment]
It would be really cool if custom Kirbytext tags could somehow accept multiline Kirbytext as parameters. Perhaps borrowing from [YAML multiline syntax](http://www.yaml.org/spec/1.2/spec.html#id2760844) with a `>` or `|`:

```
(figure: |
	(image: sloth-climbing-tree.jpg alt: A sloth climbing a tree)
caption: |
	Sloths are *great* climbers.

        **Media:** Joe Bloggs
)
```

At this point I'm considering abandoning Kirbytext for ordinary static HTML. It would then be nice to have a blueprint textarea field option for `content-type` with `html`, `kirbytext` and `text` as options, so dragging and dropping images could generate plain HTML, Kirbytext, or do nothing accordingly.

**Comment by shoesforindustry** [comment]
To be honest, I'd see why you would want this, but I'd be against this. I like the simplicity of Kirby and I'd even like to see less kirbytext and more straight markdown/multimarkdown ;-) Mind you I' also like to see proper multimarkdown/YAML variables/front matter at the top of a page rather than the current format, but I guess that is not going to happen either... other CMS's are available that maybe can do this?

**Comment by lukasbestle** [comment]
I agree with @shoesforindustry. Kirbytext tags are for rather simple stuff (simple tag arguments that can produce a rather complex output). Adding multiline stuff to them is not worth it IMHO.

But I think that the solutions I proposed are quite clean and reflect the Kirby philosophy. Storing a resource together with its metadata is DRY, whereas your solution results in different metadata wherever you embed something.

**Comment by jaydenseric** [comment]
@shoesforindustry Agreed, I prefer to lean on the more common Markdown syntax where possible. This issue is a Markdown deficiency more than anything. Markdown is stuck in the HTML4 era and not much is being done to roll out support for HTML5 features such as figures.

@lukasbestle The resources file proposal sounds like a variation of current solution number 2, just with the resources held as files instead of listed in a Structure field.

There are a lot of reasons you might not want your figure's caption to not be DRY. An image's alt text should be DRY, because a literal description of the image is inherent to the asset. A caption is not necessarily. It explains the image in the context of it's use in the article.

Kirby is a brilliant writing platform and a lot of people use it to write fairly in depth articles. HTML5 figures are the appropriate way to mark up quotes, tables and all sorts of flowing content (that markdown extra can already handle) that would be pretty cumbersome to have to manage as separate resources.

**Comment by lukasbestle** [comment]
That's true. It depends on the use-case.

But as you say, it's a very difficult problem. Markdown does not have a syntax for figures, which complicates everything even further.

**Comment by kybradeck** [comment]
Nearly 4 years later, are we closer to a solution for this? I'm struggling with a similar issue.

I have images with rich captions and I'm also attempting to conditionally lazyload different filetypes. Right now every figure is in its own snippet, composed as HTML and embedded using a [snippet tag](https://forum.getkirby.com/t/embedding-snippets/900). Is there a better way?

**Comment by lukasbestle** [comment]
The cleanest way would be a custom plugin with your own custom figure syntax like this:

```
(figure: my-image.jpg)
This is the caption.

It can have multiple lines and even *formatting*.
(...figure)
```

The [columns plugin](https://github.com/getkirby-plugins/columns-plugin/blob/master/columns.php) can be an inspiration on how to implement something like this. In case you need help, feel free to ask in our [forum](https://forum.getkirby.com).
