### ISSUE TITLE
User sortable checkbox fields

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#366]
Just an idea and I don't know how difficult it is to implement. But it would be great if checkbox options could be sorted by the user, e.g. for sorting the order in which snippets appear on the page etc.

**Comment by AugustMiller** [comment]
This could be done with a combination of select menus and the `structure` field… Although you may have to do some damage control in the view, so you're not accidentally outputting things twice.

**Comment by distantnative** [comment]
Do you already have an idea how/where to store this order, @texnixe?

**Comment by texnixe** [comment]
I had completely forgotten about this. But the order should definitely make it into the content file in this case, otherwise it would not make sense.

**Comment by distantnative** [comment]
Only that with checkboxes, usually only the selected ones go into the content file. How to determine how the unselected ones have been sorted?

**Comment by texnixe** [comment]
Good point. The sort order of the unselected ones does not matter, only if they are selected. Think of a sidebar for which users can select different snippets (e.g. a calendar, authors, tag cloud) that they can also put into a desired order.

**Comment by distantnative** [comment]
Okay, so unselected will always default to the order as they do now. Selected come first and are displayed and saved in the order how the user drags and drops them. Should be an optional feature I guess?

**Comment by texnixe** [comment]
Yes, optional.
