### ISSUE TITLE
Formatting toolbar in structure view

### ISSUE THREAD

**Issue by dinko** [getkirby-v2/panel#371]
In the structure view, textareas are missing the formatting toolbar as on "standard" textarea fields. Would be nice to have them there as well, especially for editors not so fond of syntax writing.

![bildschirmfoto 2015-02-26 um 12 18 11](https://cloud.githubusercontent.com/assets/61015/6391011/be31167c-bdb1-11e4-85e7-7c59d9a3f5d6.png)

**Comment by bastianallgeier** [comment]
They are intentionally switched off here, because the panel does not support a second level of modals so far. This is not ideal yet. I will try to find a fix for it.
