### ISSUE TITLE
Textarea field: insert file dropdown/button

### ISSUE THREAD

**Issue by dinko** [getkirby-v2/panel#373]
I really like the draggable images!

But sometimes it happens that the image list is outside the viewport. Nobody likes typing image filenames, so it would be awesome if the images or files or whatever else can be dropped into the text is also accessible at your textarea.

Quick mockup: there could be some sort of fixed toolbar next to the textarea or some dropdown that inserts an image tag or something like that.

Or…just came to my mind…additionally some way of copying the kirby tag from the image in the list.

![bildschirmfoto 2015-02-26 um 12 31 35](https://cloud.githubusercontent.com/assets/61015/6391275/eec39514-bdb4-11e4-94e8-c26ff99cfe3a.png)

**Comment by texnixe** [comment]
I support this request, it is indeed not only a problem that the files are out of view but dragging them into the text box becomes a pain as well.

**Comment by distantnative** [comment]
With the upcoming 2.2 the sidebar is fixed so that the files won't be outside the viewport anymore. I renamed this issue to make it focus on the requested file selector button/dropdown.

**Comment by dinko** [comment]
Sounds great! Thx.
