### ISSUE TITLE
Better site and image kirbytext referencing

### ISSUE THREAD

**Issue by xu-chris** [getkirby-v2/panel#415]
Actually when I want to set a reference for an image in my text I simply drag and drop the image into the editor. That is really great even when I can not specifically drop it where I want to while I'm dragging the image (maybe a focus issue?). 

But that solution isn't so helpful in some situations: 
- when you're in a structure item
- when the textfield is somewhere after scrolling meters of fields ;-)
- when I don't want to reference a child site but a parent site (or any other).

In my opinion it needs something better than just dragging from the sidebar. Many other CMS like Wordpress are giving you the possibility to choose a reference through a modal panel. I don't have the one golden way or a solution for this but I think there has to be something that matches the quality of Kirby itself. I can't say to my clients to use Kirbytags because they hate to code. Also because they would need a handbook beside them to look for the syntax - and a handbook is really 90s...

**Comment by distantnative** [comment]
+1

Also do not have a good solution at the top of my head right now, but I will give it some thought. Would be nice to find a more intuitive - or just less-scrolling-ish solution :)

**Comment by tweh** [comment]
How about an autocompletition? If i type `(image:` I get a small menu with all possible file names.

(But I have no idea if this is possible …)

**Comment by JimmyRittenborg** [comment]
:+1:
