### ISSUE TITLE
Add backup or export feature

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby-v2/panel#42]
Just a little brainstorming here...

In my opinion implementing a backup or maybe an export feature would be super cool! Virtually all my clients ask for a backup feature, because they feel kinda unsafe when editing pages without knowing there's a backup.

I really don't want most of my clients to use FTP. Sadly, most of them only use shared hosting accounts, so this issue is not easily solved through using git on the server. And of course I don't want to backup sites manually over and over again.

Any opinions or clever ideas?

**Comment by jenstornell** [comment]
I agree with @iandoe that it would be good as a plugin, but not as a core feature. If crew agree with this, close it?
