### ISSUE TITLE
Why is the login cookie set only for the session?

### ISSUE THREAD

**Issue by eytanbiala** [getkirby-v2/panel#438]
The cookie is set for the session only, so logins aren't persisted after closing and re-opening your browser.
If this is by design, can we make it an optional config setting?

**Comment by Targoran** [comment]
+1 on this. Would really appreciate to stay logged in longer than one session, especially during development.

**Comment by Denney** [comment]
The ability to have a "Remember Me" style option would be brilliant (and a timesaver). Maybe make it an optional variable we could pass to the $user->login() function.

**Comment by IamAdamJowett** [comment]
The remember me option seems like the most obvious, and most main stream of the solutions to me.

**Comment by ausminternet** [comment]
+1

**Comment by jonsecchis** [comment]
+1 need this badly

**Comment by bastianallgeier** [comment]
This is by design so far, but I will add a high prio to this for the release after the next one.

**Comment by afbora** [comment]
+1 good idea!
