### ISSUE TITLE
Number field: 0 not working as default

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/panel#497]
> tried to set a "0" as a default value of a text/number field in a blueprint... does not work for "0" but for "00", "1" and everything else.
> 
> ```
>   backgroundvideooffset:
>     label: Start offset
>     type: number
>     default: 0
> ```

**Comment by distantnative** [comment]
Has been added to the develop branch and will be part of an upcoming release.

**Comment by janstieler** [comment]
Hi,
was this fixed in the Kirby Release?
I have an Kirby2.5.12 where the problem with an 0 default value exist.

Toolkit Version: 2.5.12
Kirby Version: 2.5.12
Panel Version: 2.5.12

**Comment by texnixe** [comment]
Works for me in a 2.5.12 Starterkit.
