### ISSUE TITLE
Trigger panel.page.update hook when cache.autoupdate ?

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby-v2/panel#525]
Will this make sense or is additional hooks like `kirby.cache.set` `kirby.cache.autoupdate` planned for this ? :smiley:

**Comment by bastianallgeier** [comment]
Super late to the party, but the cache hooks sound like a better solution to keep the panel and core decoupled. I will start adding core hooks with the next release.

**Comment by JimmyRittenborg** [comment]
Sounds great :+1:
