### ISSUE TITLE
Possibility to delete multiple files at once

### ISSUE THREAD

**Issue by iksi** [getkirby-v2/panel#526]
Would it be straightforward to implement the possibility to delete multiple files at once in the thumbnail file view?

**Comment by bastianallgeier** [comment]
It wouldn't be straightforward but definitely a good idea!! I will try to find a better way to handle this. But you will definitely like the new context menus in the upcoming release, which will already make it easier.

**Comment by bastianallgeier** [comment]
ups, had my fat fingers on the wrong button :)
