### ISSUE TITLE
Auto replacing of HTML entities vs. parenthesis in Kirbytags

### ISSUE THREAD

**Issue by tweh** [getkirby-v2/panel#537]
Hi,

as it is [kind of problematic](http://forum.getkirby.com/t/way-to-use-parenthesis-inside-kirbytag/861) to use parenthesis in Kirbytags, I tried to use the HTML entities `&lpar;`/`&rpar;` but unfortunately the panel converts all HMTL entities on save to normal (UTF) characters. Is there a way to prevent this A) in general and B) for special entities like the ons for parenthesis?

To reproduce this behavior: Go to the panel and type a text like

```
This is a (link:http://getkirby.com text:link with &lpar;parens&rpar; in) it.
```

on save this will be converted to

```
This is a (link:http://getkirby.com text:link with (parens) in) it.
```

and then mess up the Kirbytag mechanism.

By,
Tobi

**Comment by inacho** [comment]
I have a similar problem with code blocks.

When I save code blocks like this one:

    ```html
    <a href="#test" title="This is an &quot;example&quot;">Link</a>
    ```

The panel converts the entities:

    ```html
    <a href="#test" title="This is an "example"">Link</a>
    ```

It would be nice to have an option to disable the conversion of html entities.
