### ISSUE TITLE
remove custom strings on URL generation for SEO and file system limits / limit length

### ISSUE THREAD

**Issue by Stolzenhain** [getkirby-v2/panel#542]
When generating the URL from the title, it would be cool to be able to configure a list of with strings that should be removed from the folder name and be able to limit URLs to a maximum number of letters. 

In practice, this is often used on SEO-friendly URLs, [Drupals Pathauto](https://www.drupal.org/project/pathauto) for example supplies a list like this:

> an, as, at, before, but, by, for, from, is, in, into, like, of, off, on, onto, per, since, than, the, this, that, to, up, via, with

to strip unneccessary words. 

We worked on project where long titles (for publication / project lists) generated unneccessary long URLS that became hard to handle on a Windows machine due to the long titles generated in the panel and the folder name limit on Windows. 

I don't know if the panel has some sort of separate configuration file (`blueprints/site.php`?), otherwise options like this should maybe be stored with each templates blueprint?

**Comment by bastianallgeier** [comment]
Good idea! I will keep this on my list for future enhancements

**Comment by jenstornell** [comment]
Then it will need to know every unneccessary word for every language in the world.

-1 (downvote) from me

**Comment by Stolzenhain** [comment]
Sorry, you misunderstood: This is about 2 custom options of the panel URL generator like: 

````yaml
- 'UrlRemoveStrings' : 'an,as,at,the,–,–'
- 'UrlMaxIdLength' : '60'
````
it would not be meant to be shipped – obviously this is different on every project.

**Comment by jenstornell** [comment]
#### UrlRemoveStrings

@Stolzenhain Maybe I was a little bit quick on the judgement. If it's just a setting for the current project with own custom words, then I'm up for it. +1 for that then...

#### UrlMaxIdLength

I'm still not sure about the limit. I don't think a cut url would look good. If it's long one it needs to be manually rewritten anyway, I think. Another problem is that if two almost identical long urls are cut they might be duplicate if only the last words are unique.

**Comment by JimmyRittenborg** [comment]
I think that the panel by default, should make the most intelligent decision about this, and then people with interests in URLs and SEO can overwrite or opt-out of it, because if there's something clients just NEVER pays attention to, it's URLs and alt attributes 😆

**Comment by Stolzenhain** [comment]
Mhh, I wouldn't even include the file; maybe just hint the option. This is basically only interesting for people handling large URLs (like publications as titles) or SEO optimization. 

Same with the maxlength … it obviously only takes effect on setting a value; which shouldn't be set as default anyway.

**Comment by Stolzenhain** [comment]
Mhh, the longer I think about it, this shouldn't reside in core anyway – didn't panel introduce plugin hooks?
