### ISSUE TITLE
Fileexplorer

### ISSUE THREAD

**Issue by schurb** [getkirby-v2/panel#559]
Dear Santa ...

wouldn't it be nice to have a file explorer for all the files that were uploaded? So I don't have to dig into each page and search for my file. 
Wouldn't it be nice to edit or replace or delete a file just like pages? It works there really great. 

Perhaps you can think about it :)

[Explanation for the Santa thing here](http://forum.getkirby.com/t/file-explorer-for-kirby/2083/5?u=schurb)

**Comment by bastianallgeier** [comment]
This is an idea I have on my list for quite a while. I will try to add this to one of the next updates.

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by schurb** [comment]
:+1:

**Comment by rmngrc** [comment]
:+1:

**Comment by Mattrushka** [comment]
:+1:

**Comment by alkinkasap** [comment]
👍
