### ISSUE TITLE
Request link for reset password

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#568]
Be able to request a password reset link to the user mail address. Never give the password, just a reset link for it.

https://forum.getkirby.com/t/kirby-panel-forgot-password/2192/13

Because of discussion, make it optional by config.php.

``` php
c::set('password.link', true);
```

**Comment by buditanrim** [comment]
I am frustated with this, in local development. Once a week it is asking me for login and I never can get it through, it's weird.

Please update the "forgot/reset passowrd"

**Comment by SQbiz** [comment]
+1, even for small or single-user sites, as a user I would expect this to be available

**Comment by texnixe** [comment]
Are there any plans to implement a password reset option - as an optional feature to be configured via the config.php - in the near future?

**Comment by jenstornell** [comment]
An alternative for a built in solution could be to allow plugins to do things around the login form. If that would be possible a plugin creator could create a plugin for resetting the password.

Maybe it's seen as a big security risk to have plugins here, but I think every plugin is the same kind of risk as long as they have PHP access which all of them have.

Anyway, that would lift this issue of the shoulders of the crew. Maybe we would see new fancy plugin solutions as well, like fingerprint login etc...

**Comment by olach** [comment]
Just leaving a comment here to bump this issue. I think this is an important feature to have in core. In my own experience with a lot of WordPress-sites, my clients often requests new passwords. (WordPress notifies the admin account whenever a user requests a new password, and it is quite often I get these notifications.)

Now, when I'm building my first Kirby site, I'm a little worried of this issue, that the clients have to contact me whenever they can't login because of a forgotten password.

**Comment by jenstornell** [comment]
I think it's possible already to make a plugin that does this, if you don't want to wait for it. To do that, make a route like `/reset/(:any)` where `(:any)` is the username. Then a mail will be sent to that user email with a link to another route like `/reset/(:any)/(:any)` where the last `(:any)` is a generated secret. When the correct url is entered the password is reset.

**Comment by texnixe** [comment]
While we are waiting for a core solution: check out this thread in the forum: https://forum.getkirby.com/t/forgot-password-feature-for-my-customers/6372

**Comment by gerritvanaaken** [comment]
+1 for a proper core solution! This is basic panel stuff!

**Comment by stereonom** [comment]
👍  no plugin solution plz.

**Comment by abegehr** [comment]
bump 👍

**Comment by SaanDigital** [comment]
+1
