### ISSUE TITLE
Clone pages feature request

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/panel#577]
Moving and clonning pages are so practical for us on duplicating smiliar pages. Move pages feature is opened here https://github.com/getkirby/panel/issues/67

Clone pages feature would be great! What do you think?

**Comment by dgdsp** [comment]
+1

**Comment by bastianallgeier** [comment]
Yes, that's definitely on my list for one of the next releases.

**Comment by jenstornell** [comment]
Agree! I added a topic this summer about it in the forum:
https://forum.getkirby.com/t/panel-duplicate-page/1505

**Comment by frekw** [comment]
Has there been any progress on this? Seems it didn't make the cut for Kirby 2.3.
