### ISSUE TITLE
Search cuts result

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#584]
I added "Project A" up to "Project G". When searching for "Project" it shows only up to "Project D". When clicking enter I expected it to show all the result in a full panel page. It did not work like that.

**How can I find "Project G" by searching for just "Project"?**

No pagination, no search result page on enter.

![image](https://cloud.githubusercontent.com/assets/927011/10665342/c2799aa4-78ca-11e5-93b3-8202c4e4dee1.png)

**Comment by bastianallgeier** [comment]
Well, the search so far only shows 5 entries per category. It might make indeed sense to offer a way to expand the results. I will think about it.
