### ISSUE TITLE
Add custom routes

### ISSUE THREAD

**Issue by alexcarrega** [getkirby-v2/panel#602]
Is it possible to add custom additional route for the panel part only?

**Comment by lukasbestle** [comment]
What is your use case? Do you want to create a field that dynamically gets information from the backend?

**Comment by alexcarrega** [comment]
I would like to extend the panel with custom options without implementing these ones as pages.
I am trying the understand how the panel routing is designed through reverse engineering but I think that it is very difficult to add custom routes.

**Comment by lukasbestle** [comment]
You can create a route in a Kirby plugin that checks whether the `Panel` class exists. Example:

```php
kirby()->routes(array(
  array(
    'pattern' => 'whatever', 
    'action' => function() {
      if(!class_exists('Panel')) {
        return go('/');
      }
      
      return response::json($whatever);
    }
  )  
));
```

**Comment by alexcarrega** [comment]
Thanks. I check if my idea can be implemented correctly.
