### ISSUE TITLE
Feature request: Page field with the fetch option of a Select field

### ISSUE THREAD

**Issue by jensfranke** [getkirby-v2/panel#656]
It would be great to have a Page field with the fetch option of a Select field.

What do you think?

**Comment by bastianallgeier** [comment]
What would be a typical use case? I can imagine that it could be cool, but I'm not 100% convinced yet :)

**Comment by jensfranke** [comment]
The fetch-option of the select field is nice, but sometimes there are still to much entries for a select field (more than 20 from my point of view). 

The autocompletion-option of the page field is great but it fetch the pages from the whole site and the results could be more accurate if you can define a scope for the search.

**Comment by bastianallgeier** [comment]
Great idea!! In general all the fieldoptions for select fields, radio buttons, etc. should be applicable to the autocompleter for the page field. That totally makes sense. Will add it to the list for 2.3

**Comment by jensfranke** [comment]
Oh, that would be great!
