### ISSUE TITLE
Feature request: min dimensions for files 

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby-v2/panel#661]
Moved from here: https://github.com/getkirby/kirby/issues/321

**Comment by distantnative** [comment]
What would be the blueprint syntax?

So far we have
```
files
  width: 300
  height: 200
```
for maximum values.

We could say maximum is the default if not specified, otherwise:

```
width:
  min: 100
  max: 500
``

Would have the benefit of being able to specify a min and max.

Then again, I am wondering if it is actually that good to have `width` and `height` on the same "option level" as `type` and `size`. Since they only refer to images.

**Comment by JimmyRittenborg** [comment]
Regarding the option level. (and correct me if this is already possible) But maybe it could be crafted in a way which would also allow for only attach fields for certain file types, as a pretty common custom alt or caption field only makes sense for images.

**Comment by texnixe** [comment]
@JimmyRittenborg  If you think alt and caption, you are right. But meta data can be useful for any kind of files you add to your page, be it pdf or downloads or whatever.

**Comment by distantnative** [comment]
I still think it would be an interesting idea to define file fields per file type.

**Comment by texnixe** [comment]
Oh absolutely, I misread @JimmyRittenborg's post, I'm afraid.

**Comment by jenstornell** [comment]
+1 for min dimensions

Maybe also take care of exact dimension matches like:

```
width:
  min: 100
  max: 100
height:
  min: 200
  max: 200
```

In this case the user probably want to only allow an exact match like 100 x 200.

**Comment by malvese** [comment]
Would have loved this feature in a current project. I added instructions in an `info` field instead, but users can still ignore them.

**Comment by texnixe** [comment]
Wait for permissions ...;)
