### ISSUE TITLE
Move Subpages to different Folder

### ISSUE THREAD

**Issue by benseitz** [getkirby-v2/panel#67]
In the file system you can easily move a subfolder to another folder.

For example the subpage "ProjectX" from "Active Projects" site to "Old Projects".

I think it would be nice if you could do this also from the backend.

**Comment by seehat** [comment]
Isn't there a setting to make sure that the subpage's template is allowed?

https://getkirby.com/docs/panel/blueprints/subpages-settings#templates-for-subpages

**Comment by jenstornell** [comment]
@seehat 

**Possible problems that comes to mind:**

- Complex nested structures maybe add problems.
- Move large files. At least copy many large files can be a problem. I'm not sure about move.
- Collisions. It needs to be sure that no other page gets overwritten.
- Move with success. It needs to be sure that all the files are moved and are not corrupt.
- Leave no data behind. It also needs to be sure that the old page is deleted.

The new template switcher is a good step where you can see what will change on a template change. Maybe do something similar with move?

A traditional file manager could `add`, `delete`, `rename`, `copy` and `move` stuff. It would be cool to have a CMS that could do those things as well. :)

**Comment by Sija** [comment]
Hi @bastianallgeier!

I'm seriously considering using Kirby for my next project, that is portfolio of my photographer friend.
To make it versatile I'd need to provide him ability to move files and pages within the folder structure.
Imagine being unable to move photo from one folder to another... that's quite insane, especially when you'd use it for modelling galleries. Of course he could download the image and upload it again in different place, but when you use metadata attached to the file, the whole process involves as well manually copying value of every field, which makes it unusable in real-world scenarios.

Any plans on implementing it in the near future?

**Comment by puckey** [comment]
Although I understand the complexities involved, I would like to add a huge +1 for this feature request. It is something my editors regularly need to do. More often then not, I find myself doing it for them through FTP.
