### ISSUE TITLE
Filter users by role [feature requests]

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/panel#695]
I think users can be filterable on panel like only admins or only editors listing.

What do you think about?

Thanks

**Comment by texnixe** [comment]
You can filter users by role:

```php
<?php foreach($site->users()->filterBy('role', 'admin') as $user) {
	echo $user->username();
}
?>
```

**Comment by bastianallgeier** [comment]
Yes, that's something I had in mind for a while and never really managed to implement.
