### ISSUE TITLE
textarea in structure field strips leading/trailing space in all lines

### ISSUE THREAD

**Issue by tweh** [getkirby-v2/panel#714]
While #322 deals with the stripping of spaces at the end and beginning of fields this issue is about indention in the middle of a `textarea` field content used in a `structure` field. In this case all leading (and trailing) spaces from all lines get lost on save. Which is kind of annoying since in markdown nested lists and code are marked by indention.

**How to reproduce?**
1. Download the 2.2.3 starter kit
2. add
   
   ``` plain
   mystructure:
     label: Structure
     type: structure
     entry: {{text}}
     fields:
       text:
         label: Text
         type: textarea
   ```
   
   to `blueprints/default.php`
3. Open panel and edit the about page; add
   
   ``` plain
   ···some·text···with···
   ······spaces···
   ·····leading·and
   trailing···
   and·in······between
   ```
   
   (`·` = space) in a structure entry
4. save
5. open `content/1-about/default.php`.

The text is saved as

``` plain
-·
··text:·|
····some·text···with
····spaces
····leading·and
····trailing
····and·in······between
```

while it should be

``` plain
-·
··text:·|
·······some·text···with···
··········spaces···
·········leading·and
····trailing···
····and·in······between
```

or at least (regarding #322)

``` plain
-·
··text:·|
····some·text···with···
··········spaces···
·········leading·and
····trailing···
····and·in······between
```

I.e. only spaces between the words are preserved, while all leading and trailing spaces are stripped.

---

FYI: In 2.1.2 the result of saving the _first_ time is

``` plain
-·
··text:·|
·······some·text···with···

··········spaces···

·········leading·and

····trailing···

····and·in······between
```

but when saved the second time (without changes in the panel) the result is

``` plain
-·
··text:·|
····some·text···with
·······spaces
······leading·and
····iling
·····in······between
```

this result is stable and doesn’t change on further save.

**Comment by tweh** [comment]
- [ ] z

**Comment by tweh** [comment]
Sorry this was by accident O:-)

**Comment by distantnative** [comment]
Not sure if this can be fixed easily since (as far as I am aware) YAML uses indentation for its structure. And since structure fields are saved as content in a YAML style, it'd be hard to identify what spaces are indentation for YAML and which ones belong to the input. Anyone has ideas how to deal with this?

**Comment by lukasbestle** [comment]
I found [this on StackOverflow](http://stackoverflow.com/a/30679252). Maybe some of that in combination can solve this problem.

**Comment by OlegIvaniv** [comment]
Any news about this bug?

**Comment by lukasbestle** [comment]
No, unfortunately not. This is something that would need to be changed in the Spyc YAML library, but as we wrote above, the YAML syntax is unfortunately not really suited for multiline text with indentation, so I can't say what the intended behavior would be.
