### ISSUE TITLE
Warning for out-of-sync blueprints (content file values with no blueprint representation)

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/panel#753]
Connected to #368 - the current version preserves extra fields in the content file that are not specified by the blueprint. It just keeps them instead of deleting them. It could be a nice addition if the panel would show a little warning/notification that the content file contains some out-of-sync fields/values that have no representation in the blueprint.

**Comment by bastianallgeier** [comment]
Could make sense to bind this to the admin role. Normal editors would probably get confused by it. But in general it's a good idea.
