### ISSUE TITLE
Structure field: get rid of modals

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/panel#767]
Having structure fields with modals causes quite a few problems, complications etc. How about getting rid of them?

When clicking the Add button, it could just toggle the structure field form fields to slide in between the add button heading and the already existing structure field content. Same when editing, let the entry fade out and slide in the form fields.

Thoughts?

**Comment by texnixe** [comment]
Absolutely +1

**Comment by jenstornell** [comment]
+1

**Comment by ralfgoeke** [comment]
+1

generally modals are painful in many ways and should be avoided whenever possible. Here's a nice link to some general design patterns to avoid modals. https://developer.appway.com/screen/ShowSingleRecipe/selectedRecipeId/1390246496349

**Comment by jenstornell** [comment]
Advanced Custom Fields for Wordpress uses accordians and it works really well.

**Comment by medienbaecker** [comment]
+1
This sounds way more convenient and also resolves some issues with the modals and custom fields like https://github.com/JonasDoebertin/kirby-visual-markdown/issues/76

**Comment by samnabi** [comment]
+1!

**Comment by A-Monkey** [comment]
+ 1000 !
Yeah I hate modals ; ) It always feels like a "emergency solution" !!

**Comment by fabianmichael** [comment]
+1

**Comment by jakobploens** [comment]
+1

**Comment by TheSmithy** [comment]
+1

**Comment by aoimedia** [comment]
+1. I really like the sound of this.

**Comment by jdvivar** [comment]
+1

**Comment by puckey** [comment]
+1

**Comment by Thiousi** [comment]
+1

**Comment by bugsysop** [comment]
+1

**Comment by p-h-i-l** [comment]
+1 and add support for nested structured fields...

**Comment by thiebou** [comment]
+1

**Comment by ldanielswakman** [comment]
+1

**Comment by mpatzner** [comment]
+1

**Comment by Mojo90** [comment]
+1

**Comment by luismqueral** [comment]
+1 🌻

**Comment by Mattrushka** [comment]
+1

**Comment by christophfranke** [comment]
+1
