### ISSUE TITLE
"page" field not working like search

### ISSUE THREAD

**Issue by medienbaecker** [getkirby-v2/panel#769]
The search on the top right was updated in 2.2.0. Prior to this update you could only search by the full URI of a page. It's way faster now, since you can also just type the slug of the page.

While similar in functionality, the "page" field was not updated to work like that. You still have to enter the whole URI, parent by parent, to select the page.

https://getkirby.com/docs/cheatsheet/panel-fields/page

**Comment by distantnative** [comment]
This might go a complete different way: https://twitter.com/getkirby/status/706135619152572416
