### ISSUE TITLE
Empty Structure fields fall back to default language

### ISSUE THREAD

**Issue by moritzz** [getkirby-v2/panel#792]
### Introduction

I assumed, that if you translate pages with structure fields, it's possible to have structure content in the default language page and keep the same structure field empty for a translation of the same page. Unfortunately, this is not the case:
### Bug

If you add structure to a content in one language and keep the same structure field empty in the page translation, both Panel and Kirby Core fall back to the structure content of the default language instead of an empty structure when loading the translation in the Panel _or outputting the page as front-end_. 

This prohibits having the same structure field failed in the default language but empty in a translation.

**Comment by bastianallgeier** [comment]
This is not a bug but a feature. Well, it's more like a decision I made in the beginning when implementing multi-lang stuff. I thought it would always be better to have a fallback for empty translations, but sometimes it really doesn't make sense. I wasn't able so far to figure out a system, which provides fallbacks easily, but also handles empty fields correctly. Any suggestions are highly appreciated.

**Comment by moritzz** [comment]
I'd go for not falling back on empty (structure?¹) fields with `translate: true`, but `translate: false` or introduce a `translation-fallback: [true/false]` flag. What do you think?

¹ IMHO structure fields are a special case here; because they mostly hold a load of complex data (and potentially references to other pages) that need to be translated manually anyhow, falling back to the contents of their corresponding contents in the default language isn't what one would expect. Correct me if I'm wrong. :)

**Comment by texnixe** [comment]
IMO, there is no right or wrong, and I'm not convinced that structure field content should be different from other text fields (it certainly depends on what sort of content you put into a structure field). But it would be great to have a translation-fallback option like you suggest, either on a per page or maybe even on a per field basis. 

I'm currently working on a project where I have the same problem and would like to leave some structure fields empty in the non-default language, but always get the default content.

**Comment by moritzz** [comment]
@texnixe: I agree. This issue is highly context-sensitive. My proposition for a `translation-fallback: [true/false]` was for a per-field flag, btw, similat to the existing `translate: [true|false]` field option. I even tired to explicitly set `translate: true` on my structure field, expecting that this could prevent empty field from falling back to their corresponding default language content. Leading to another approach:

- No `translate` field option value: Field can be translated, but falls back to default language, if value is empty.
- `translate` field option set to `true`: Field can be translated, but *does not fall back* to default language, if its value is empty.
- `translate` field option set to `false`: Field cannot be translated, i.e. value is the same as default language contents for all translations

This behavior would guarantee compatibility with existing instances, because one can assume with `translate` defaulting to the first behavior, no one explicitly set `translate` to `true` powered by current versions of Kirby

What do you think?

**Comment by texnixe** [comment]
Yes, I agree absolutely, that sounds like a reasonable idea. It would probably make sense on a per blueprint basis as well, but on the page level, I can currently use a workaround by filtering my content by language, so that's not really a big deal.

**Comment by distantnative** [comment]
The main problem with this is that the Kirby core handles the fallback to the default languages if a field is empty. And the core has no idea what's in the blueprints - so it would never be aware of any of these options.

I know this is a tough one. But maybe, if you know in your templates which structure fields you would not like to fallback to a default language, maybe this could work (untested)?

```php
<?php if($page->content(site()->language()->code())->get('yourStructureField')->isNotEmpty()) : ?>
  // what you wanna do with your structure field
<?php endif ?>
```

**Comment by texnixe** [comment]
@distantnative That's a valid point. I haven't tested that workaround yet, but that's what I would have tried next. Nevertheless is is quite irritating for users if a field is always refilled with content that they have just deleted.

**Comment by Sija** [comment]
@distantnative why not bring blueprints into the core?

**Comment by texnixe** [comment]
Then Kirby would not only have to read the text files but also each blueprint for a page which could become a performance issue.

**Comment by moritzz** [comment]
@Sija and @texnixe: Even though I see an issue with exposing all blueprint meta data in core, I had several other use cases where this would have come handy, let's say, getting the type of field when outputting its value. Nethertheless, I understand the performance and dependency arguments there.

Back to the original topic...

**Comment by moritzz** [comment]
Thanks @distantnative for the cope snippet; this might help us in the meantime.

**Comment by moritzz** [comment]
I do understand the arguments agains exposing blueprint meta data to core, but I strongly suggest exposing at least the information **if a field value is translated or derived from a fall back** to core.

**Comment by Sija** [comment]
@texnixe and what about adding `blueprint()` method to page model which would lazy-load blueprint metadata (and cache it for later use) allowing inspection without performance cost (how high is it?) of executing the call blindly for every model? In this way decision would be left to the user, better choice IMO.

**Comment by texnixe** [comment]
@Sija: [see this post in the forum](https://forum.getkirby.com/t/add-a-new-field-method-in-the-kirby-code/3548/3)

**Comment by moritzz** [comment]
@Sija: Please, keep the threads clean; this issue is not about blueprint access in core. No offense. Thanks, M.

**Comment by bastianallgeier** [comment]
Would it help to have something like

```php
$page->myfield()->isTranslated()
```

?

**Comment by Sija** [comment]
@bastianallgeier I'd say YES :)

**Comment by distantnative** [comment]
`$page->myfield()->isTranslated()` just got added to the develop branch. I think in combination with the fixed `translation: false` blueprint option, this should solve this issue.

**Comment by moritzz** [comment]
You rock!

**Comment by moritzz** [comment]
There still is a connected issue in Panel though; if you switch the language of a page to translate all structure fields get the values from the default language pre-filled. Saving the translation you end up with all structure fields set to the values of the default language on any translation.

**Comment by moritzz** [comment]
Actually that was the bug, I reported to begin with. Any thought on that one?

**Comment by texnixe** [comment]
That's what I was just about to say, the new methods, while nice, does not help with fields - structure or not - that get refilled with content from the default language (i.e. fields without the option translate: false, which may or may not have a translation)

**Comment by distantnative** [comment]
But as @bastianallgeier has elaborated, this is not a bug but a design decision of Kirby: Kirby will fall back to the default language if the field is empty for the current language. So if you do not want this default feature behaviour for some part of your site, you need to check for that. and with this new introduced method, you can do this now fairly easily:

```php
if($page->myStructureField()->isTranslated()) {
  // what you want to do with your structure field
}
```

This will enable you to leave the structure field empty for a certain language without displaying the fallback from the default language. Or have you any suggestions how to handle your case in another way without reverting the general design of Kirby's language fallback?

**Comment by texnixe** [comment]
@distantnative : Well, yes, the new method actually compares strings, so that in fact even if the value of the default language is saved, this default value will not be displayed on the site. That's good.

But: I still find it very irritating for users that even if they delete the contents of a field in the non-default language and save, as soon as they save, the content reappears in the form field. 

When I think about it, it does indeed make sense to show the contents of the default language, so that the user knows what sort of content needs to be translated. However, in some contexts, an option to change this default behavior of showing the default content with a `show-default: false` would leave it to the developer to show/not show the untranslated contents for the non-default languages in the panel.

**Comment by moritzz** [comment]
Wow, @texnixe, `show-default: false` in combination with `isTranslated()` would save our day. Thanks for coming up with such an elegant approach. Cheers, M.

**Comment by distantnative** [comment]
I will have a look on how to implement it. I'm afraid modifying $field->value() could break/not work for a lot of custom fields tho. And can we have a different name for the option? Something that refers to translations?

**Comment by texnixe** [comment]
Maybe something like `translation-fallback: show/hide`?

**Comment by distantnative** [comment]
I'm wondering if we could re-use the `translate` option to not introduce just another one. `translate: true` is the oldest state where empty fields are filled with defaults but lets you set a translation. `translate: false` completely blocks translation, so it always falls back to the default language. And maybe `translate: optional` allows translation but will not fill the fields with the default language, so you can save them empty and then use $field->isTranslated()?

**Comment by moritzz** [comment]
Ha!, @distantnative:

> I even tired to explicitly set `translate: true` on my structure field, expecting that this could prevent empty fields from falling back to their corresponding default language value, leading to another approach:
> 
> - No `translate` field option value: Field can be translated, but falls back to default language, if value is empty.
> - `translate` field option set to `true`: Field can be translated, but *does not fall back* to default language, if its value is empty.
> - `translate` field option set to `false`: Field cannot be translated, i.e. value is the same as default language for all translations.
> 
> This behavior would guarantee compatibility with existing instances, because one can assume with `translate` defaulting to the first behavior, no one explicitly set `translate` to `true` on sites powered by current versions of Kirby

**Comment by jenstornell** [comment]
I just askes about the same thing here:

https://forum.getkirby.com/t/disable-autocopy-in-multi-language/3634

I think it's great that there is a solution on the way. I like how it's solved, so keep that.

However, on my site I want to completely disable "autocopy". I've got 26 blueprints with about 20 fields in each of them. That means I need to add `translate: optional` on 520 places (when not using blueprint snippets).

**I would therefor want something like this in the config:**

```
c::set('translate', 'optional');
```

It would just have all fields fallback on that option if no other option is set in the blueprint.

**Comment by Thiousi** [comment]
Hello,
I've ran into this same issue today and found it hard to understand for the user. Any updates on implementing the new behavior ?

**Comment by flokosiol** [comment]
Same here … 

I think the values of the default language should be inherited **while creating** the new translation (the moment you change the language in the panel and there's no textfile for this language yet). **But** if you hit save for the first time and the new textfile for this language is created, there shouldn't be any inheritance from the default language anymore ... unless you use `translate: false` of course.

I like the approach mentioned by @moritzz [above](https://github.com/getkirby/panel/issues/792#issuecomment-196230016).

**Comment by texnixe** [comment]
Hope this will make it into 2.5?

**Comment by distantnative** [comment]
I also think @moritzz's suggestion still is the most charming one.

**Comment by lukasbestle** [comment]
`translate: optional` just made it to the develop branch for 2.5.3. :)

**Comment by moritzz** [comment]
You all rock. Thanks a lot for improving Kirby’s world class I18n features. Yours sincerely, Moritz

**Comment by benegan1991** [comment]
Feel like this option has been removed now?
