### ISSUE TITLE
Cannot make any edits after setting the language of the site.

### ISSUE THREAD

**Issue by ponychicken** [getkirby-v2/panel#797]
On my client sites I would like to use the lang attribute of the html tag.
When I define the default language of a site though, the panel is unable to make edits anymore.

I set the language in the config likr this:

```
c::set('languages', array(
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'default' => true,
    'locale'  => 'de_DE',
    'url'     => '/',
  )
));
```

The panel still shows the content of he pages correctly, but after clicking save the textfield
silently reverts to its previous state, without any error message. Most likely due to the fact that the content files are named page.txt and not page.de.txt.

My suggestion: On save, the panel should save the file and make sure the name is what is expected by kirby, renaming it if necessary.

**Comment by texnixe** [comment]
Hm, if I'm not mistaken, you end up with two files, a filename.de.txt and a filename.txt. So the content is saved to the correct file but the filename.txt is loaded to show the content. This is due to the fact that you can't have more than one text file in a folder if it does not have a language (or file-extension) extension. Kirby can't really know what language the previous filename.txt extension is supposed to be, at least not if you add more than one language.

**Comment by ponychicken** [comment]
Yeah, you're right, it saves it to .de.txt, but then continues to display the plain .txt
Should the editor load de.txt afterwards, since I set it as the default language?

**Comment by texnixe** [comment]
You have to delete the page.txt file without the extension, otherwise the Panel does not work correctly. This issue occurs if you start out with a standard installation and then switch to multi-language. It should actually have been documented in the language docs, I think.

**Comment by ponychicken** [comment]
So basically the bug is this: 
On a multilang setup (no matter if actually there are multiple languages or just one) the multilang page class (/kirby/branches/multilang/page.php) loads sets the content file for the default language to the "unextended" (page.txt) file if it exists, instead of picking the proper extension (page.langcode.txt).

This leads to seemingly disappearing edits: Edits are saved correctly to page.langcode.txt, but the panel and the site display page.txt instead. The bug seems to be in the `ìnventory``method, but might be deeper still.

**Comment by lukasbestle** [comment]
As @texnixe wrote, this is not a bug and is [documented in the languages docs](https://getkirby.com/docs/languages/setup#attention-switching-from-singlelanguage-to-multilanguage). You need to rename the files to make it work properly.

**Comment by ponychicken** [comment]
Even if documented I would classify it still as a bug. I enter some text, press save, I get the ok smiley, and the text appears without explanation.

**Comment by texnixe** [comment]
Maybe this old feature idea could help if it gets implemented: https://github.com/getkirby/panel/issues/266

As I said above, this is probably an issue that needs manual intervention from the developer rather then some automated assumptions.

**Comment by ponychicken** [comment]
Submitted a PR here: https://github.com/getkirby/kirby/pull/400
