### ISSUE TITLE
panel language switch is applied to other tabs/windows without feedback

### ISSUE THREAD

**Issue by GeraldGrote** [getkirby-v2/panel#824]
If a user has two instances of the panel in multiple browser-tabs or windows and switches the language in one of them, the language change gets applied to the other tabs of the browser session. The new language is not shown in these tabs before a reload, but changed content will get saved with the new language overwriting the old one. This leads to content loss when working with multiple tabs.

To prevent this, the panel could save the content in the language still visible in the tab before switching to the new language and/or give feedback, that the language has been changed in another window and enforce a reload.

**Comment by jenstornell** [comment]
https://forum.getkirby.com/t/language-switch-in-panel-with-multiple-browser-tabs-windows/3825
