### ISSUE TITLE
Sort hook is not triggered if the sort is pushed by another page

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#827]
If I drag the page `a11` in this case, then the sort hook for `a11` is triggered.

When I drag `aaa` up to position 1 then `a11` is pushed down. `a11` change sort number, yet the sort action is not triggered for that, only for `aaa` even if both of them are affected.

![image](https://cloud.githubusercontent.com/assets/927011/14493639/bb0f80c2-0186-11e6-9c23-0b1df8888c0f.png)

I know why it work like this, but how should we else hook it, when the sort number is changed to a page that is pushed around by another page?

My suggested solution is that the took is triggered for all affected pages, all pages that have their sort number changed.

**Comment by lukasbestle** [comment]
I can reproduce this. This happened to me as well and I share your suggestion.

**Comment by bastianallgeier** [comment]
I'm really not sure about this. I think another hook could work, but if I modify it as you suggested, the hook could easily be called a couple dozen if not hundred times with many pages. Does that really make sense? And how do you find out which is the main page, that has just been sorted? 

I think one of those two could work as name.

- panel.page.reorder
- panel.page.renumerate

This additional hook would be called whenever the number has been changed. What do you think?

**Comment by jenstornell** [comment]
**Real case**

A while ago when I was working on https://github.com/jenstornell/kirby-revisions I wanted to change the revisions in sync with the pages that changed. With the current hook that was not possible. In cases like this I think it make sense. Maybe it means introducing new hooks.

However I skipped the sort part completely with my plugin so it's not very important personally right now. But there will probably be more cases like it.

I don't know the difference with `reorder` and `renumerate`. I like the sound of `reorder` better. As long as the hooks are named well, don't be afraid to create new ones.
