### ISSUE TITLE
panel.page.create hook in a not default language get wrong textfile

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#830]
**I use this setup in the config.php**

``` php
c::set('languages', array(
  array(
    'code'    => 'en',
    'name'    => 'English',
    'default' => true,
    'locale'  => 'en_US',
    'url'     => '/',
  ),
  array(
    'code'    => 'de',
    'name'    => 'Deutsch',
    'locale'  => 'de_DE',
    'url'     => '/de',
  ),
));
```

And this in a a plugin.

``` php
kirby()->hook('panel.page.create', function($page) {
  echo $page->textfile(); // It cannot echo here. Figure out another way to see it
});
```
1. Switch to `de` in the panel, another language than default.
2. Create a new page in `de` that does not already exists in `en`.
3. See what the `$page->textfile()` generates. For me it is `default.de.txt`.
4. See what is created in the `content` folder. For me it is `default.en.txt`.

It creates `default.en.txt` but outputs `default.de.txt`.

**Comment by texnixe** [comment]
From what you are saying above, `$page->textfile()` outputs the right file, but the wrong one is created? Do you mean the other way round? When I create a new page in a non-default language, both text files are created, the one for the default language and the one for the current language.

**Comment by jenstornell** [comment]
Yes, it can be the other way around depending on how you look at it. Did you follow my instructions exactly? Are you using Kirby 2.3 beta? Forgot to mention that I do.

1. When the panel is `de` and I create a new page `default.en.txt` is created. Nothing more. That's ok because it's empty. Are you sure you also get `default.de.txt` directly?
2. When I save the `de` page for the first time (update it), then it's created because then at the first time it will be different from `default.en.txt`.

Make sure that:

- Kirby 2.3 beta is used.
- Panel is set to a none default language, like `de` in this case.
- Create a new page but don't update it with content.

**Comment by texnixe** [comment]
I removed my comment again, because the de version is only created once the content is actually saved, so yes, you are right. In fact, I think both textfiles should be created when I create a de (or any other non-default) version of a page.

**Comment by jenstornell** [comment]
So create current langauge textfile  + default textfile on create. Sounds good to me. Then it would automatically solve this issue as well because then the file would be found.

**Comment by texnixe** [comment]
It's no a problem of the hook, though, because even if you echo `$page->textfile()` in a template, it outputs the textfile of the current language, no matter if that file actually exists or not.

**Comment by jenstornell** [comment]
If we solve it your way, then there is no problem with the hook.

It's only if it would be solved differently or not at all the problem appear. What's important to me in this case is that the `$page->textfile()` should lead to a real content file that actually exists.

Rename this issue if you think it has the wrong focus.

**Comment by texnixe** [comment]
The `textfile()` method is probably not the right one to use here, because it's really sort of stupid; it just returns what you tell it to return;) You should maybe rather use the `$content->root()` method here?

**Comment by jenstornell** [comment]
Yes, using `$page->content()->root()` seems to work like I expect.
