### ISSUE TITLE
Respect child blueprint in "Add a new page" dialog: title field

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/panel#845]
See [this topic](https://forum.getkirby.com/t/panel-add-help-text-to-new-page-dialog/4030?u=lukasbestle).

**Comment by puckey** [comment]
Same goes for the Title label – when I specify it in the blueprint, I would expect to see it in the "Add a new page" dialog's title input field

**Comment by lukasbestle** [comment]
The issue here is that the "Add a new page" dialog isn't fixed to a specific template but the user can select the template. This means that the Panel will need to make a request when changing the selected template to get the data from the blueprint.
Works, but is some work to implement. So I don't think we can expect this soon.
