### ISSUE TITLE
Slug javascript generator only replaces first item

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#853]
**With the default Kirby Panel I set this page title:**

```
Lösöga
```

**I expect it to be:**

```
loesoega
```

**Instead it's like this:**

```
loesga
```

So, only the first `ö` is replaced in the slug, not the rest.

**Another example:**

```
Hähähähähähäh
```

**Results in:**

```
haehh-h-h-h-h
```

**Comment by texnixe** [comment]
I wonder if this is related: https://github.com/getkirby/panel/issues/724

**Comment by jenstornell** [comment]
**I don't thing so. I tried it now with "normal" characters:**

I replaced `test` with `haha` by overriding the array like discussed in this post: https://forum.getkirby.com/t/strange-slug-translation-of-a/1493/4

**Page title**

```
testtesttest
```

**Replaced `test` with `haha`**

```
hahatesttest
```

It only replaces it one time.

**Comment by afbora** [comment]
https://github.com/getkirby/panel/issues/773

**Comment by jenstornell** [comment]
@distantnative @afbora 

Yes, it seems to be the same issue.

However I don't think it has anything to to with special characters. See my test above.

If you want to close this issue, make sure to copy my previous post because it proves that it's not a special character problem.
