### ISSUE TITLE
Problem with panel.page.update hook

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#855]
https://forum.getkirby.com/t/panel-page-update-hook/4273

**Comment by H-i-red** [comment]
Any time frame when this can be looked at ?
Need it pretty badly..

**Comment by texnixe** [comment]
With the hook in question, the panel get's into an endless spin, because it is triggered over and over.

**Comment by texnixe** [comment]
Since the `$page->update()` does not trigger `panel.page.update` there should be no endless spin, if that is what happens here. Maybe it is something else after all.

**Comment by lukasbestle** [comment]
The reason is most likely that a `$page` in the Panel is a different object as a `$page` in Kirby. So if a Panel hook is called, the param will be a Panel `$page`, which will trigger hooks on updates. I think we should pass normal Kirby page objects to hooks to prevent that.
