### ISSUE TITLE
disabled datetime not disabled at all

### ISSUE THREAD

**Issue by stereonom** [getkirby-v2/panel#858]
when you create a datetime field (havn't tested with date and time) and you set your blueprint to `disabled: true` it is styled as disabled but you can still change the the values.

![image](https://cloud.githubusercontent.com/assets/883533/15702971/3ff73104-27e3-11e6-9142-ad7482546f85.png)

**Comment by lukasbestle** [comment]
This applied only to the datetime field. The reason was that the value of the `disabled` option wasn't passed to the child fields date and time.

This is now fixed and will be included in Kirby 2.3.1.

**Comment by mrflix** [comment]
Though disabled the time field is black:
![screen shot 2017-03-13 at 15 20 43](https://cloud.githubusercontent.com/assets/60777/23858424/a594273a-0800-11e7-9d91-9324df4d9420.png)
