### ISSUE TITLE
Don't save content of readonly field in content file

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#869]
https://forum.getkirby.com/t/blueprint-field-readonly-writes-to-disc-on-save/4427/3

Related to https://github.com/getkirby/panel/issues/688

**Comment by jenstornell** [comment]
https://forum.getkirby.com/t/blueprint-field-readonly-writes-to-disc-on-save/4427

**Comment by bnomei** [comment]
any fix planed for 2017?
