### ISSUE TITLE
Wrong sortable offset when scrolled down in panel

### ISSUE THREAD

**Issue by TimOetting** [getkirby-v2/panel#884]
Fields that use jquery ui sortable, like the structure field, encounter a bug of jquery ui: 

If you have to scroll down inside the panel on a page (i.e. you scroll down the .mainbar container that wraps the right column in the panel) and then drag an item for the first time it has an offset to the mouse position that is the same amount of pixels like the scroll offset of .mainbar. As a result, the dragged element is positioned below the mouse cursor. When you drag the item around and trigger some interaction with the other items in the sortable list, it jumps back to the correct position. This only occurs at the first drag after reloading the page.

This bug somehow has to do with the .mainbar as a scrollable container for the sortable. It seems to still take the body as a reference for its position. But only when the first dragging happens...

I somehow fixed it by adding some more options to my sortable. However, this is kind of a dirty solution and still gives me some glitches:

``` javascript
    var offsetFix = true;
    element.find('.mySortable').sortable({
      start: function(e, ui){
        if(offsetFix){
          ui.item.css('margin-top', -$('.mainbar').scrollTop() );
        }
      },
      change: function(e, ui){
        if(offsetFix){
          ui.item.css('margin-top', 0);
          offsetFix = false;
        }
      },
      stop: function(e, ui){
          offsetFix = false;
      },

[...]
```

Do you still have a change of the drag & drop library on your todo list? I think this would be the best solution for this.

**Comment by caseyryan** [comment]
I've got the same issue. You're solution resolves the problem, despite some aother minor issues. Thanks!
