### ISSUE TITLE
Pagination doesn't appear on pages widget.

### ISSUE THREAD

**Issue by LCD344** [getkirby-v2/panel#885]
In panel when you have more pages the  pagination allows. The pages widget paginates the pages, but doesn't print out the navigation bar.

the reason is that in widgets/pages/pages.php the template is loaded like this

```
return tpl::load(__DIR__ . DS . 'pages.html.php', array(
      'pages' => $site->children()->paginated('sidebar')
));
```

but it seems that the pagination itself isn't passed to the view. And the view doesn't refer to pagination at all

widgets/pages/pages.html.php

```
<ul class="nav nav-list sidebar-list">
  <?php foreach($pages as $c): ?>
  <?php echo new Kirby\Panel\Snippet('pages/sidebar/subpage', array('subpage' => $c)) ?>
  <?php endforeach ?>
</ul>
```

**Comment by sebsel** [comment]
Bumping this, because I'm running into this too. When a site has 20+ pages, it will just show the first 20 and hides the rest. (That is: 20+ subpages of the root, direct children of `/content/`.)

The solution for now is to click 'edit' or on the 'Pages' head, to go to `/panel/site/subpages`. There, the whole thing is visible.

Might be good to add a `more >` link / button at the bottom of the widget linking to that same page? Or indeed add pagination to the widget.

**Comment by LCD344** [comment]
@sebsel - if you want to fix it for yourself you can do this -

in panel/app/widgets/pages/pages.php

`<?php 

$site    = panel()->site();
$options = array();

if($site->canHaveSubpages()) {
  $options[] = array(
    'text' => l('dashboard.index.pages.edit'),
    'icon' => 'pencil',
    'link' => $site->url('subpages')
  );
}

if($addbutton = $site->addButton()) {
  $options[] = array(
    'text'  => l('dashboard.index.pages.add'),
    'icon'  => 'plus-circle',
    'link'  => $addbutton->url(),
    'modal' => $addbutton->modal(),
    'key'   => '+',
  );
}

return array(
  'title' => array(
    'text'       => l('dashboard.index.pages.title'),
    'link'       => $site->url('subpages'),
    'compressed' => true
  ),
  'options' => $options,
  'html'  => function() use($site) {
    return tpl::load(__DIR__ . DS . 'pages.html.php', array(
      'pages' => $site->children()->sortBy('title')->paginated('sidebar')
    ));
  }
);`

and in panel/app/widgets/pages/pages.html.php

`<ul class="nav nav-list sidebar-list">
	<?php
	foreach ($pages as $c) {
		echo new Kirby\Panel\Snippet('pages/sidebar/subpage', ['subpage' => $c]);
	}
	?>
</ul>
<?php if ($pages->pagination()->hasPages()) { ?>
	<nav class="pagination" style="text-align: center">
		<a class="pagination-prev<?= !$pages->pagination()->hasPrevPage() ? ' pagination-inactive' : '' ?>"
		   href="<?= $pages->pagination()->prevPageURL() ?>">
			<span><i class="fa fa-arrow-left" aria-hidden="true"></i>Previous Page</span>
		</a>

		<span class="pagination-index" style="left: auto; right: auto; display: inline">
		<?php foreach ($pages->pagination()->range(5) as $page) { ?>
			<a href="<?= $pages->pagination()->pageURL($page) ?>" style="display: inline;<?= ($pages->pagination()->page() != $page) ? 'color: gray' : ''?>"><?= $page ?></a>
		<?php } ?>
		</span>
		<a class="pagination-next<?= !$pages->pagination()->hasNextPage() ? ' pagination-inactive' : '' ?>"
		   href="<?= $pages->pagination()->nextPageURL() ?>">
			<span>Next Page <i class="fa fa-arrow-right" aria-hidden="true"></i></span>
		</a>
	</nav>
<?php } ?>
`

@texnixe - do y'all accept pull requests? if so, Ill make on with this code.

**Comment by texnixe** [comment]
@LCD344 Looks like your code in pages.php is based on an old version of the file? The function `canHaveSubpages()` doesn't exist anymore…

And yes, we do [accept pull requests](https://github.com/getkirby/panel/pulls?q=is%3Apr+is%3Aclosed)

**Comment by LCD344** [comment]
You are very right... it is based on old code apparently, I just made a pull request with the new code though :)
