### ISSUE TITLE
Panel File Upload Hook doesn't work…

### ISSUE THREAD

**Issue by Foddy** [getkirby-v2/panel#898]
Hi,

I don't know if I am doing something wrong, but I am trying to optimize an image after uploading from the blogger to the panel backend. I am using the current version 2.3.1 of KirbyCMS.

I created a plugin in **"site/plugins/imageupload/imageupload.php"**

This plugin is loaded correctly by the backend (I tried the die() method), but the hook doesn't trigger properly? Everytime I upload an image on the backend nothing happens, I mean I don't get any custom code execution?

```
kirby()->hook('panel.file.upload', function($file) {
      die('JUST TO TEST');
});
```

**Comment by lukasbestle** [comment]
You can't really test this with `die()` as the Panel returns JSON data to the client. A better way to test if a hook is run is to save a file somewhere, like:

```php
kirby()->hook('panel.file.upload', function($file) {
  f::write(kirby()->roots()->index() . DS . 'test.txt', $file->root());
});
```

This should create a file `test.txt` in the root of your site with the file path to the uploaded file.
