### ISSUE TITLE
Tags field: Vertical bar (|) as separator (Kirby 2.3.2)

### ISSUE THREAD

**Issue by andreasnymark** [getkirby-v2/panel#931]
Seems like the vertical bar (|) is not working as a separator in the tags field.

**Comment by distantnative** [comment]
I'd guess this is the sae as #759 - potential fix in #761 (tho maybe outdated)

**Comment by andreasnymark** [comment]
I’m not sure it’s the same, but it might be. The text string is not split into separate tags instead it’s looking something like this http://cloud.nymark.me/KzLKA6PG.png

**Comment by distantnative** [comment]
Also after hitting the save button?

**Comment by andreasnymark** [comment]
Yes.

**Comment by distantnative** [comment]
Then it is not the same
