### ISSUE TITLE
Idea: save image width and height on upload/replace

### ISSUE THREAD

**Issue by iksi** [getkirby-v2/panel#932]
Long story short: I made a big big performance gain doing the following, so I just want to put it out there as an idea/enhancement.

I recently found `getimagesize` to be an enormous bottleneck on a project I was working on. This project deals with a lot of images.

The `getimagesize` function gets called via `dimensions()` in `Media` (kirby/toolkit/lib/media.php). The retrieved dimensions apparently get cached with `$this->cache['dimensions']` but I couldn’t really figure out how this cache works or how long it persists. Calling `getimagesize` on a lot of images can be quite expensive, especially on slower servers: sometimes I had request latency going through the roof (12 seconds and more) as I’m using `$file->width()` and `$file->height()` on each image. After finally having found out this was causing the problems I was having I wrote a simple panel hook that saves the width and height of each image on upload and replace into two fields: `wide` and `tall` (as I can’t reuse width and height). Now I use these with `$file->wide()` and `$file->tall()` and latency dropped dramatically.

The issue was very hard to pinpoint as after the initial use of `dimensions()` the dimensions get cached. Still the initial load of the page can be slow as `getimagesize` is getting called on each image. And as soon as `$this->cache['dimensions']` expires the same slow page load occurs it’s slow again. Feedback from users and my client was that the website was sometimes fast and sometimes extremely slow.

**Comment by lukasbestle** [comment]
`$this->cache['dimensions']` is just a memory cache, it doesn't get persisted. Meaning: It "expires" on every page load. You are right that it might make sense to cache the image meta data somewhere else. But that's something for the core, not the Panel.
