### ISSUE TITLE
Kirby 2.3.2 Value of field with option "translate: false" disappears in non-default language

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#937]
https://forum.getkirby.com/t/strange-structure-behaviour-in-2-3-2/5542/9

Edit: Seems to be intentional behaviour, but the behavior is somehow irritating in structure fields.

**Comment by bastianallgeier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kirby 2.3.2 Value of field with option "translate: false" disappears in non-default language](https://trello.com/c/lnmAgf9A/10-kirby-2-3-2-value-of-field-with-option-translate-false-disappears-in-non-default-language)
