### ISSUE TITLE
Panel sidebar page widgets in the blueprint. THE solution?

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#940]
https://forum.getkirby.com/t/panel-sidebar-page-widgets-in-the-blueprint-the-solution/5563

In short...

**Blueprint**

``` text
title: Projects
fields:
  title:
    label: Title
    type: text
widgets
  page_settings:
    label: Page settings
    type: page_settings
  my_custom_widget:
    label: My custom widget
    type: my_custom_widget
  pages:
    label: Pages
    type: pages
  files:
    label: Files
    type: files
```

> Jens, I think you actually really nailed it. This is bloody brilliant. I will need to think about it a bit more, but it actually solves quite a lot of issues.

**Comment by bastianallgeier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Panel Sidebar Widgets](https://trello.com/c/m5hDqNDt/6-panel-sidebar-widgets)
