### ISSUE TITLE
Don’t remove template from panel when only one template is allowed

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#942]
https://forum.getkirby.com/t/dont-remove-template-from-panel-when-only-one-template-is-allowed/5624
## Summery

When I'm on a panel page where it's only allowed to have one template, the template selector choice is missing. That makes sense because I'm not allowed to use another template.

The downside is that I get no information on what template the page is using. I can't select another one but I still want information of what I'm using.
## Solution

![image](https://cloud.githubusercontent.com/assets/927011/19805948/d2d0c3d8-9d17-11e6-9cf1-ec9257b330b6.png)

**Comment by bastianallgeier** [comment]
I was actually thinking about keeping all the options there, even if they are inactive and rather have a more visible way to show they are deactivated (maybe with strike through text or something)

**Comment by jenstornell** [comment]
Having all visible all the time would probably be more consistant. You don't need to look for someting that is simply not there and it can be good for debugging too.

![image](https://cloud.githubusercontent.com/assets/927011/19958178/640985cc-a19d-11e6-93bf-49ea353f535f.png)

There are still a few things I don't like about that.

## I often use options set to false, to hide stuff

For me personally, I often set options to false, not to disable the functions, but to hide the things I don't need in the sidebar. That gives me more space for the things I do need, like pages and files.

From that aspect it would be a degration from the current usage.

## Strikethrough text

With strikethrough text it's really clear that the text below does not apply. Still there are two things I don't like about it:

- The text is harder to read. For example I think `opacity: .5 ` is easier to read.
- When I tried it in the panel I also discovered that with a really quick look I did not notice there was a strikethrough text. It could make it hard to discover which items are true and which are false. I'm quite sure it's because both states are using the same black color.
- The icon to the left is not strikethrough so it still looks allowed to click on.

## Suggestions

### Make it possible to show/hide

I use the true or false to hide stuff for most part. To not make it less of that than today here is one solution.

- In the options, have an option to make it visible or not., as a complement.
- Look at `template`, it has false set directly. So both new version and old version is working.

```yml
options:
  preview:
    available: true
    visible: true
  status:
    available: true
    visible: false
  template: true
```

As always, I'm not sure about the keys/names.

The downside would be that there are more stuff in the options, but because it works with the old version as well, it's only when needed.

### Transparent or red for false

Instead of strikethrough text maybe the item can be transparent (like the initial screenshot in the post) or the red color from the panel. I think it's more readable.

### Collapse/modal

I think the best way to go is by the blueprint. If you disagree, an alternative could be a collapsed part or a modal fired by a click to show the false option data.

## Widgetized sidebar version

I don't know how far you have been thinking about it, but if you will allow widgets and customize them in the blueprint I think it can look kind of like this:

```yml
title: Projects
fields:
widgets:
  page_settings:
    label: Page settings
    type: page_settings
    options:
      preview:
        available: true
        visible: true
      template: true
  pages:
    label: Pages
    type: pages
```

All the options are now bound to the `page_settings` widget.

It would be a breaking change but I think it would be more consistant to have the options bound to the widget that is using them. In the current blueprint the options is global in that perspective.

But because it's a breaking change I'm aware that it's not as easy to change without "breaking a few eggs".
