### ISSUE TITLE
Select field default does not work in this case

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#967]
Kirby 2.4.0

**This works:**

It's using a key/value pair for the option that also is a default value.

```text
target:
    label: Target
    type: select
    default: _self
    options:
      - _blank
      _self: _self
      - _parent
      - _top
```

This way also work for the selectbox, but does not select the default value:

```text
  target:
    label: Target
    type: select
    default: _self
    options:
      - _blank
      - _self
      - _parent
      - _top
```

**Two possible solutions:**

1. Make both select options continue to work + make default value work as well.
1. Don't make the default value work + don't make the options to work.

All or nothing. I vote for the first solution.

**Comment by lukasbestle** [comment]
It's difficult as the default option needs the key. If we'd support values as well, it would be inconsistent.

Until we have a proper solution for this, you can also use `default: 1` to make the second option the default (remember: `default` needs the key, and the key of a value without explicit key is its numeric key).

**Comment by jenstornell** [comment]
In the second example I think the values could act both as keys and as values.

In the code, maybe check if it's a key+value, or just if it's just a value. If just a value, then set a key to the same value as the value. I mean, force a key+value pair out of it first.

**Comment by lukasbestle** [comment]
We had the same issue with YAML keys/values in another GitHub issue recently. We just can't reliably detect if the user used just values or if actually using numeric keys is intended, like this:

```
  target:
    label: Target
    type: select
    default: _self
    options:
      0: _blank
      1: _self
      2: _parent
      3: _top
```

It's a limitation of PHP's data structure.

**Comment by jenstornell** [comment]
Ahh, now I understand the problem.
