### ISSUE TITLE
Pagination arrows at subpages sidebar widget ignore c::set('url')

### ISSUE THREAD

**Issue by jakobploens** [getkirby-v2/panel#990]
A client just reported the following issue to me: the pagination arrows within the subpages widget seem to ignore the `c::set('url')` setting. The setting is here used to make sure the website is running under the 'www' subdomain (internal redirects in the client's network make this necessary that they can visit their website without problems). The pagination arrows ignore this and show the usual url without www – therefore, the other pages can't be accessed through visual links. I'm not sure if this is just a panel problem or even just within the subpages, I haven't yet tested other cases.

**Comment by jimhaakman** [comment]
I have the same issue on a docker installation.
