### ISSUE TITLE
search on enter

### ISSUE THREAD

**Issue by puckey** [getkirby-v2/panel#992]
Currently search works by sending a separate search request for every keystroke as a user types a search query.

This has a severe impact on sites with hundreds of pages.

Would it be possible to either [debounce](https://davidwalsh.name/javascript-debounce-function) the search requests or allow an option to perform a single search on 'enter' button?

**Comment by LeBenLeBen** [comment]
I have the same issue and as @puckey said, one solution would be to debounce the key event before sending the request. In addition, I think it should also abort any on going request if a new one is sent. Those two things can be easily done looking at the existing code.

I would be happy to submit a PR to improve this but I’m not very comfortable with the current JavaScript setup. Is the file [jquery.autocomplete.js ](https://github.com/getkirby/panel/blob/master/assets/js/src/jquery/plugins/jquery.autocomplete.js) specific to Kirby Panel or is a vendor? Do you agree to modify it or do you have another approach to suggest? @texnixe @bastianallgeier
