### ISSUE TITLE
Running Panel tests

### ISSUE THREAD

**Issue by pedroborges** [getkirby-v2/panel#994]
When stumbling on a bug in Kirby I'm always happy to dig deeper trying to find a solution myself. Recently I tried to add a test to the Panel test suite before start digging but I couldn't run them on my machine.

The `composer.json` doesn't include any dependencies needed in order to run tests so I guess that might have to do with me having the newest version of PHP and PHPUnit, or may be missing some other tool. I tried with PHP 7.0.8 and PHPUnit 5.7.5. The error I got is:

```shell
PHP Fatal error:  Cannot declare class Site, because the name is already in use in /Users/pedro/Code/plainkit/kirby/branches/default.php on line 16

Fatal error: Cannot declare class Site, because the name is already in use in /Users/pedro/Code/plainkit/kirby/branches/default.php on line 16
```

It would be great to have that info added somewhere. I'm looking into adding tests to my plugins.

**Comment by bezin** [comment]
Could you please provide the code of your test as well?

**Comment by pedroborges** [comment]
I actually didn't get into writing tests. I trying running the tests the Panel ships with. I'm still trying to understand how to bootstrap Kirby for testing with it.

**Comment by bezin** [comment]
Ahh ok, I see – I run the tests successfully yesterday though. Did you try to run them in a fresh Kirby working copy or in a project you are working on?

**Comment by pedroborges** [comment]
Yep, I tried on a clean install. Could you please share which PHP and PHPUnit versions you have installed?

**Comment by bezin** [comment]
PHP 5.6.16 / PHPUnit 5.7.4

**Comment by pedroborges** [comment]
I just uninstalled PHP 7 and installed 5.6 but still no luck. I have PHPUnit 5.7.5. Am I missing something?

```shell
kirby install -k plainkit
cd plainkit
phpunit -c panel/phpunit.xml
```

It outputs:

```shell
PHP Fatal error:  Cannot redeclare class Site in /Users/pedro/Code/kirby-test/kirby/branches/default.php on line 16

Fatal error: Cannot redeclare class Site in /Users/pedro/Code/kirby-test/kirby/branches/default.php on line 16
```

**Comment by pedroborges** [comment]
This runs the Toolkit tests just fine, even though 2 tests failed.

```shell
phpunit -c kirby/vendor/getkirby/toolkit/phpunit.xml
```

**Comment by lukasbestle** [comment]
Strange, your shell script works on my machine. We are in the process of improving automatic unit tests, so we will look into this at some point.

**Comment by bezin** [comment]
Despite the fact I cannot reproduce the above mentioned issue, I can't run the tests msyself though ^^

I get the following error in almost every test, except the ones in PanelTest (since no admin is created there):
```
1) AutocompleteTest::testUsernames
Exception: The user could not be found

C:\development\kirby2\panel\app\src\panel.php:545
C:\development\kirby2\panel\app\src\panel\collections\users.php:27
C:\development\kirby2\panel\tests\lib\testcase.php:91
C:\development\kirby2\panel\tests\tests\AutocompleteTest.php:9
```

**Comment by lukasbestle** [comment]
Yes, I have the same issue. But the tests themselves run. Looks like there is an issue with the test setup.

**Comment by bezin** [comment]
[See issue happens, when panel()->user() is called without argument.](https://github.com/getkirby/panel/blob/master/app/src/panel/collections/users.php#L27
) That's why $username defaults to null and the exception is thrown.
