### ISSUE TITLE
Page field called "form" breaks the panel

### ISSUE THREAD

**Issue by mzur** [getkirby-v2/panel#997]
If I create a `form` page field, the panel breaks:

```
Whoops\Exception\ErrorException Missing argument 1 for Kirby\Panel\Models\Page::form(), called in .../panel/app/src/panel/models/page/changes.php on line 71
````

![error](https://cloud.githubusercontent.com/assets/2457311/22107641/4eb019d6-de4f-11e6-839a-ba2bce6628be.png)

It probably happens because the field is called as a magic method (`$page->form()`) but the `form` method already exists. Maybe creating page fields with names that clash with existing page methods can be forbidden somehow?

**Comment by texnixe** [comment]
There was some discussion about this in the past, see also the docs on naming: https://getkirby.com/docs/panel/blueprints/form-fields#field-names. In most cases you can use existing page methods as field names, but with some, it does not work.

**Comment by mzur** [comment]
Right but what prompted me to open an issue about this is that the panel is permanently broken once this error occurs. I think the page/blueprint is cached in the session and not always updated so you have to change the blueprint, navigate somewhere else in the panel by manipulating the URL, log out and log in again to fix this. This is a rather bad user experience and I wondered if this error could be handled more gracefully (e.g. with a `method_exists` check when the blueprint is loaded).
